{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "871dd8de-8e03-4a7f-a6e2-b9cf555019d8",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "UTILS CONFIG LOADED SUCCESSFULLY\nPROJECT_NAME: brazil_legislative_analytics\nPROJECT_VERSION: v1.0.0\nPROJECT_ENVIRONMENT: dev\nCATALOG_NAME: brazil_legislative_analytics\nRUN_ID: 2a34f1fc-c4b2-4b28-8d94-66b55f988fcc\n"
     ]
    }
   ],
   "source": [
    "%run ../99_utils/utils_config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "e6efc69b-eb36-437c-8fed-745a98bcfc9c",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "UTILS CONFIG LOADED SUCCESSFULLY\nPROJECT_NAME: brazil_legislative_analytics\nPROJECT_VERSION: v1.0.0\nPROJECT_ENVIRONMENT: dev\nCATALOG_NAME: brazil_legislative_analytics\nRUN_ID: b4581acb-ac78-4a69-963e-1f4f5390c58b\n"
     ]
    },
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "utils_quality loaded successfully.\n"
     ]
    }
   ],
   "source": [
    "%run ../99_utils/utils_quality"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "7b02ae0c-1adf-4cd8-99e4-bb3cce3cb5ff",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "==========================================================================================\nBRAZIL LEGISLATIVE ANALYTICS MEDALLION\n01 - QUALITY BRONZE CHECKS\n==========================================================================================\nExecution Timestamp: 2026-05-20 03:11:00.341811\nCatalog: brazil_legislative_analytics\nLayer: bronze\n==========================================================================================\n==========================================================================================\nRunning Bronze quality checks for: brazil_legislative_analytics.bronze.br_deputados\n==========================================================================================\n==========================================================================================\nRunning Bronze quality checks for: brazil_legislative_analytics.bronze.br_frentes\n==========================================================================================\n==========================================================================================\nRunning Bronze quality checks for: brazil_legislative_analytics.bronze.br_frentes_membros\n==========================================================================================\n==========================================================================================\nRunning Bronze quality checks for: brazil_legislative_analytics.bronze.br_frentes_detalhes\n==========================================================================================\n==========================================================================================\nRunning Bronze quality checks for: brazil_legislative_analytics.bronze.br_eventos\n==========================================================================================\n==========================================================================================\nRunning Bronze quality checks for: brazil_legislative_analytics.bronze.br_votacoes\n==========================================================================================\n==========================================================================================\nRunning Bronze quality checks for: brazil_legislative_analytics.bronze.br_votos\n==========================================================================================\n==========================================================================================\nRunning Bronze quality checks for: brazil_legislative_analytics.bronze.br_despesas_ceap\n==========================================================================================\n==========================================================================================\nRunning Bronze quality checks for: brazil_legislative_analytics.bronze.br_cpis\n==========================================================================================\n==========================================================================================\nRunning Bronze quality checks for: brazil_legislative_analytics.bronze.br_cpi_eventos\n==========================================================================================\n==========================================================================================\nRunning Bronze quality checks for: brazil_legislative_analytics.bronze.br_proposicoes\n==========================================================================================\nBronze quality results persisted into: brazil_legislative_analytics.audit.aud_log_qualidade_dados\n"
     ]
    },
    {
     "output_type": "display_data",
     "data": {
      "text/html": [
       "<style scoped>\n",
       "  .table-result-container {\n",
       "    max-height: 300px;\n",
       "    overflow: auto;\n",
       "  }\n",
       "  table, th, td {\n",
       "    border: 1px solid black;\n",
       "    border-collapse: collapse;\n",
       "  }\n",
       "  th, td {\n",
       "    padding: 5px;\n",
       "  }\n",
       "  th {\n",
       "    text-align: left;\n",
       "  }\n",
       "</style><div class='table-result-container'><table class='table-result'><thead style='background-color: white'><tr><th>qlt_id_log</th><th>aud_id_execucao</th><th>aud_tx_nome_projeto</th><th>aud_tx_versao_pipeline</th><th>aud_tx_ambiente</th><th>aud_tx_nome_notebook</th><th>aud_tx_nome_camada</th><th>aud_tx_nome_entidade</th><th>aud_tx_tabela_destino</th><th>qlt_tx_nome_regra</th><th>qlt_tx_descricao_regra</th><th>qlt_tx_status_validacao</th><th>qlt_qt_total_registros</th><th>qlt_qt_registros_invalidos</th><th>qlt_pc_registros_invalidos</th><th>qlt_dh_validacao</th><th>qlt_tx_mensagem</th></tr></thead><tbody><tr><td>94c89b59-79b8-41cb-806f-328383c17a83</td><td>b4581acb-ac78-4a69-963e-1f4f5390c58b</td><td>brazil_legislative_analytics</td><td>v1.0.0</td><td>dev</td><td>01_quality_bronze_checks</td><td>bronze</td><td>deputados</td><td>brazil_legislative_analytics.bronze.br_deputados</td><td>bronze_table_exists</td><td>Validates whether the Bronze table exists.</td><td>FAILED</td><td>1</td><td>1</td><td>100.0</td><td>2026-05-20T03:11:04.431Z</td><td>Bronze table does not exist.</td></tr><tr><td>db8ec0cb-f1b8-4250-ba29-2b50b16be03e</td><td>b4581acb-ac78-4a69-963e-1f4f5390c58b</td><td>brazil_legislative_analytics</td><td>v1.0.0</td><td>dev</td><td>01_quality_bronze_checks</td><td>bronze</td><td>frentes</td><td>brazil_legislative_analytics.bronze.br_frentes</td><td>bronze_table_exists</td><td>Validates whether the Bronze table exists.</td><td>FAILED</td><td>1</td><td>1</td><td>100.0</td><td>2026-05-20T03:11:04.431Z</td><td>Bronze table does not exist.</td></tr><tr><td>8450a16c-aa3e-48bc-b1b4-97d7c11e55d1</td><td>b4581acb-ac78-4a69-963e-1f4f5390c58b</td><td>brazil_legislative_analytics</td><td>v1.0.0</td><td>dev</td><td>01_quality_bronze_checks</td><td>bronze</td><td>frentes_membros</td><td>brazil_legislative_analytics.bronze.br_frentes_membros</td><td>bronze_table_exists</td><td>Validates whether the Bronze table exists.</td><td>FAILED</td><td>1</td><td>1</td><td>100.0</td><td>2026-05-20T03:11:04.431Z</td><td>Bronze table does not exist.</td></tr><tr><td>2986810f-eb9e-474d-a8f8-41c773d2ae3e</td><td>b4581acb-ac78-4a69-963e-1f4f5390c58b</td><td>brazil_legislative_analytics</td><td>v1.0.0</td><td>dev</td><td>01_quality_bronze_checks</td><td>bronze</td><td>frentes_detalhes</td><td>brazil_legislative_analytics.bronze.br_frentes_detalhes</td><td>bronze_table_exists</td><td>Validates whether the Bronze table exists.</td><td>FAILED</td><td>1</td><td>1</td><td>100.0</td><td>2026-05-20T03:11:04.431Z</td><td>Bronze table does not exist.</td></tr><tr><td>5e107939-fe9e-4a1d-91b4-84e1be23a704</td><td>b4581acb-ac78-4a69-963e-1f4f5390c58b</td><td>brazil_legislative_analytics</td><td>v1.0.0</td><td>dev</td><td>01_quality_bronze_checks</td><td>bronze</td><td>eventos</td><td>brazil_legislative_analytics.bronze.br_eventos</td><td>bronze_table_exists</td><td>Validates whether the Bronze table exists.</td><td>FAILED</td><td>1</td><td>1</td><td>100.0</td><td>2026-05-20T03:11:04.431Z</td><td>Bronze table does not exist.</td></tr><tr><td>18fa5efa-6c8e-4614-bfc2-dd8611e9735f</td><td>b4581acb-ac78-4a69-963e-1f4f5390c58b</td><td>brazil_legislative_analytics</td><td>v1.0.0</td><td>dev</td><td>01_quality_bronze_checks</td><td>bronze</td><td>votacoes</td><td>brazil_legislative_analytics.bronze.br_votacoes</td><td>bronze_table_exists</td><td>Validates whether the Bronze table exists.</td><td>FAILED</td><td>1</td><td>1</td><td>100.0</td><td>2026-05-20T03:11:04.431Z</td><td>Bronze table does not exist.</td></tr><tr><td>c9faf5a7-4034-46cb-a948-288be98afc52</td><td>b4581acb-ac78-4a69-963e-1f4f5390c58b</td><td>brazil_legislative_analytics</td><td>v1.0.0</td><td>dev</td><td>01_quality_bronze_checks</td><td>bronze</td><td>votos</td><td>brazil_legislative_analytics.bronze.br_votos</td><td>bronze_table_exists</td><td>Validates whether the Bronze table exists.</td><td>FAILED</td><td>1</td><td>1</td><td>100.0</td><td>2026-05-20T03:11:04.431Z</td><td>Bronze table does not exist.</td></tr><tr><td>5e26de17-42c1-4906-83d0-12682f537255</td><td>b4581acb-ac78-4a69-963e-1f4f5390c58b</td><td>brazil_legislative_analytics</td><td>v1.0.0</td><td>dev</td><td>01_quality_bronze_checks</td><td>bronze</td><td>despesas_ceap</td><td>brazil_legislative_analytics.bronze.br_despesas_ceap</td><td>bronze_table_exists</td><td>Validates whether the Bronze table exists.</td><td>FAILED</td><td>1</td><td>1</td><td>100.0</td><td>2026-05-20T03:11:04.431Z</td><td>Bronze table does not exist.</td></tr><tr><td>3c705a3d-17af-497e-876e-242c7523eac8</td><td>b4581acb-ac78-4a69-963e-1f4f5390c58b</td><td>brazil_legislative_analytics</td><td>v1.0.0</td><td>dev</td><td>01_quality_bronze_checks</td><td>bronze</td><td>cpis</td><td>brazil_legislative_analytics.bronze.br_cpis</td><td>bronze_table_exists</td><td>Validates whether the Bronze table exists.</td><td>FAILED</td><td>1</td><td>1</td><td>100.0</td><td>2026-05-20T03:11:04.431Z</td><td>Bronze table does not exist.</td></tr><tr><td>c4bd4e5a-da79-42a6-8e27-70d111ff5c5c</td><td>b4581acb-ac78-4a69-963e-1f4f5390c58b</td><td>brazil_legislative_analytics</td><td>v1.0.0</td><td>dev</td><td>01_quality_bronze_checks</td><td>bronze</td><td>cpi_eventos</td><td>brazil_legislative_analytics.bronze.br_cpi_eventos</td><td>bronze_table_exists</td><td>Validates whether the Bronze table exists.</td><td>FAILED</td><td>1</td><td>1</td><td>100.0</td><td>2026-05-20T03:11:04.431Z</td><td>Bronze table does not exist.</td></tr><tr><td>81e7bf87-39ce-4bb1-aa56-e070b1faa08f</td><td>b4581acb-ac78-4a69-963e-1f4f5390c58b</td><td>brazil_legislative_analytics</td><td>v1.0.0</td><td>dev</td><td>01_quality_bronze_checks</td><td>bronze</td><td>proposicoes</td><td>brazil_legislative_analytics.bronze.br_proposicoes</td><td>bronze_table_exists</td><td>Validates whether the Bronze table exists.</td><td>FAILED</td><td>1</td><td>1</td><td>100.0</td><td>2026-05-20T03:11:04.431Z</td><td>Bronze table does not exist.</td></tr></tbody></table></div>"
      ]
     },
     "metadata": {
      "application/vnd.databricks.v1+output": {
       "addedWidgets": {},
       "aggData": [],
       "aggError": "",
       "aggOverflow": false,
       "aggSchema": [],
       "aggSeriesLimitReached": false,
       "aggType": "",
       "arguments": {},
       "columnCustomDisplayInfos": {},
       "data": [
        [
         "94c89b59-79b8-41cb-806f-328383c17a83",
         "b4581acb-ac78-4a69-963e-1f4f5390c58b",
         "brazil_legislative_analytics",
         "v1.0.0",
         "dev",
         "01_quality_bronze_checks",
         "bronze",
         "deputados",
         "brazil_legislative_analytics.bronze.br_deputados",
         "bronze_table_exists",
         "Validates whether the Bronze table exists.",
         "FAILED",
         1,
         1,
         100.0,
         "2026-05-20T03:11:04.431Z",
         "Bronze table does not exist."
        ],
        [
         "db8ec0cb-f1b8-4250-ba29-2b50b16be03e",
         "b4581acb-ac78-4a69-963e-1f4f5390c58b",
         "brazil_legislative_analytics",
         "v1.0.0",
         "dev",
         "01_quality_bronze_checks",
         "bronze",
         "frentes",
         "brazil_legislative_analytics.bronze.br_frentes",
         "bronze_table_exists",
         "Validates whether the Bronze table exists.",
         "FAILED",
         1,
         1,
         100.0,
         "2026-05-20T03:11:04.431Z",
         "Bronze table does not exist."
        ],
        [
         "8450a16c-aa3e-48bc-b1b4-97d7c11e55d1",
         "b4581acb-ac78-4a69-963e-1f4f5390c58b",
         "brazil_legislative_analytics",
         "v1.0.0",
         "dev",
         "01_quality_bronze_checks",
         "bronze",
         "frentes_membros",
         "brazil_legislative_analytics.bronze.br_frentes_membros",
         "bronze_table_exists",
         "Validates whether the Bronze table exists.",
         "FAILED",
         1,
         1,
         100.0,
         "2026-05-20T03:11:04.431Z",
         "Bronze table does not exist."
        ],
        [
         "2986810f-eb9e-474d-a8f8-41c773d2ae3e",
         "b4581acb-ac78-4a69-963e-1f4f5390c58b",
         "brazil_legislative_analytics",
         "v1.0.0",
         "dev",
         "01_quality_bronze_checks",
         "bronze",
         "frentes_detalhes",
         "brazil_legislative_analytics.bronze.br_frentes_detalhes",
         "bronze_table_exists",
         "Validates whether the Bronze table exists.",
         "FAILED",
         1,
         1,
         100.0,
         "2026-05-20T03:11:04.431Z",
         "Bronze table does not exist."
        ],
        [
         "5e107939-fe9e-4a1d-91b4-84e1be23a704",
         "b4581acb-ac78-4a69-963e-1f4f5390c58b",
         "brazil_legislative_analytics",
         "v1.0.0",
         "dev",
         "01_quality_bronze_checks",
         "bronze",
         "eventos",
         "brazil_legislative_analytics.bronze.br_eventos",
         "bronze_table_exists",
         "Validates whether the Bronze table exists.",
         "FAILED",
         1,
         1,
         100.0,
         "2026-05-20T03:11:04.431Z",
         "Bronze table does not exist."
        ],
        [
         "18fa5efa-6c8e-4614-bfc2-dd8611e9735f",
         "b4581acb-ac78-4a69-963e-1f4f5390c58b",
         "brazil_legislative_analytics",
         "v1.0.0",
         "dev",
         "01_quality_bronze_checks",
         "bronze",
         "votacoes",
         "brazil_legislative_analytics.bronze.br_votacoes",
         "bronze_table_exists",
         "Validates whether the Bronze table exists.",
         "FAILED",
         1,
         1,
         100.0,
         "2026-05-20T03:11:04.431Z",
         "Bronze table does not exist."
        ],
        [
         "c9faf5a7-4034-46cb-a948-288be98afc52",
         "b4581acb-ac78-4a69-963e-1f4f5390c58b",
         "brazil_legislative_analytics",
         "v1.0.0",
         "dev",
         "01_quality_bronze_checks",
         "bronze",
         "votos",
         "brazil_legislative_analytics.bronze.br_votos",
         "bronze_table_exists",
         "Validates whether the Bronze table exists.",
         "FAILED",
         1,
         1,
         100.0,
         "2026-05-20T03:11:04.431Z",
         "Bronze table does not exist."
        ],
        [
         "5e26de17-42c1-4906-83d0-12682f537255",
         "b4581acb-ac78-4a69-963e-1f4f5390c58b",
         "brazil_legislative_analytics",
         "v1.0.0",
         "dev",
         "01_quality_bronze_checks",
         "bronze",
         "despesas_ceap",
         "brazil_legislative_analytics.bronze.br_despesas_ceap",
         "bronze_table_exists",
         "Validates whether the Bronze table exists.",
         "FAILED",
         1,
         1,
         100.0,
         "2026-05-20T03:11:04.431Z",
         "Bronze table does not exist."
        ],
        [
         "3c705a3d-17af-497e-876e-242c7523eac8",
         "b4581acb-ac78-4a69-963e-1f4f5390c58b",
         "brazil_legislative_analytics",
         "v1.0.0",
         "dev",
         "01_quality_bronze_checks",
         "bronze",
         "cpis",
         "brazil_legislative_analytics.bronze.br_cpis",
         "bronze_table_exists",
         "Validates whether the Bronze table exists.",
         "FAILED",
         1,
         1,
         100.0,
         "2026-05-20T03:11:04.431Z",
         "Bronze table does not exist."
        ],
        [
         "c4bd4e5a-da79-42a6-8e27-70d111ff5c5c",
         "b4581acb-ac78-4a69-963e-1f4f5390c58b",
         "brazil_legislative_analytics",
         "v1.0.0",
         "dev",
         "01_quality_bronze_checks",
         "bronze",
         "cpi_eventos",
         "brazil_legislative_analytics.bronze.br_cpi_eventos",
         "bronze_table_exists",
         "Validates whether the Bronze table exists.",
         "FAILED",
         1,
         1,
         100.0,
         "2026-05-20T03:11:04.431Z",
         "Bronze table does not exist."
        ],
        [
         "81e7bf87-39ce-4bb1-aa56-e070b1faa08f",
         "b4581acb-ac78-4a69-963e-1f4f5390c58b",
         "brazil_legislative_analytics",
         "v1.0.0",
         "dev",
         "01_quality_bronze_checks",
         "bronze",
         "proposicoes",
         "brazil_legislative_analytics.bronze.br_proposicoes",
         "bronze_table_exists",
         "Validates whether the Bronze table exists.",
         "FAILED",
         1,
         1,
         100.0,
         "2026-05-20T03:11:04.431Z",
         "Bronze table does not exist."
        ]
       ],
       "datasetInfos": [],
       "dbfsResultPath": null,
       "isJsonSchema": true,
       "metadata": {},
       "overflow": false,
       "plotOptions": {
        "customPlotOptions": {},
        "displayType": "table",
        "pivotAggregation": null,
        "pivotColumns": null,
        "xColumns": null,
        "yColumns": null
       },
       "removedWidgets": [],
       "schema": [
        {
         "metadata": "{}",
         "name": "qlt_id_log",
         "type": "\"string\""
        },
        {
         "metadata": "{}",
         "name": "aud_id_execucao",
         "type": "\"string\""
        },
        {
         "metadata": "{}",
         "name": "aud_tx_nome_projeto",
         "type": "\"string\""
        },
        {
         "metadata": "{}",
         "name": "aud_tx_versao_pipeline",
         "type": "\"string\""
        },
        {
         "metadata": "{}",
         "name": "aud_tx_ambiente",
         "type": "\"string\""
        },
        {
         "metadata": "{}",
         "name": "aud_tx_nome_notebook",
         "type": "\"string\""
        },
        {
         "metadata": "{}",
         "name": "aud_tx_nome_camada",
         "type": "\"string\""
        },
        {
         "metadata": "{}",
         "name": "aud_tx_nome_entidade",
         "type": "\"string\""
        },
        {
         "metadata": "{}",
         "name": "aud_tx_tabela_destino",
         "type": "\"string\""
        },
        {
         "metadata": "{}",
         "name": "qlt_tx_nome_regra",
         "type": "\"string\""
        },
        {
         "metadata": "{}",
         "name": "qlt_tx_descricao_regra",
         "type": "\"string\""
        },
        {
         "metadata": "{}",
         "name": "qlt_tx_status_validacao",
         "type": "\"string\""
        },
        {
         "metadata": "{}",
         "name": "qlt_qt_total_registros",
         "type": "\"long\""
        },
        {
         "metadata": "{}",
         "name": "qlt_qt_registros_invalidos",
         "type": "\"long\""
        },
        {
         "metadata": "{}",
         "name": "qlt_pc_registros_invalidos",
         "type": "\"double\""
        },
        {
         "metadata": "{}",
         "name": "qlt_dh_validacao",
         "type": "\"timestamp\""
        },
        {
         "metadata": "{}",
         "name": "qlt_tx_mensagem",
         "type": "\"string\""
        }
       ],
       "type": "table"
      }
     },
     "output_type": "display_data"
    },
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "==========================================================================================\nBRONZE QUALITY SUMMARY\n==========================================================================================\nPassed validations: 0\nWarning validations: 0\nFailed validations: 11\n==========================================================================================\nWARNING: Bronze quality validation finished with 11 failed validation(s). This is expected if Bronze tables have not been created yet.\nBRONZE QUALITY CHECKS COMPLETED\n"
     ]
    }
   ],
   "source": [
    "# Databricks notebook source\n",
    "# MAGIC %md\n",
    "# MAGIC # 01 Quality — Bronze Checks\n",
    "# MAGIC\n",
    "# MAGIC Executes data quality validations for Bronze tables in the Brazil Legislative Analytics Medallion project.\n",
    "# MAGIC\n",
    "# MAGIC ## Purpose\n",
    "# MAGIC This notebook validates whether Bronze ingestion outputs are available and structurally consistent before Silver processing.\n",
    "# MAGIC\n",
    "# MAGIC ## Scope\n",
    "# MAGIC Bronze quality checks focus on:\n",
    "# MAGIC - table existence\n",
    "# MAGIC - required traceability columns\n",
    "# MAGIC - minimum record availability\n",
    "# MAGIC - duplicated hash records\n",
    "# MAGIC - source endpoint traceability\n",
    "# MAGIC - controlled exception handling per entity\n",
    "# MAGIC\n",
    "# MAGIC ## Persistence\n",
    "# MAGIC Validation results are persisted into:\n",
    "# MAGIC\n",
    "# MAGIC ```text\n",
    "# MAGIC audit.aud_log_qualidade_dados\n",
    "# MAGIC ```\n",
    "# MAGIC\n",
    "# MAGIC ## Execution Policy\n",
    "# MAGIC During early development, Bronze tables may not exist yet.\n",
    "# MAGIC In this case, validations are persisted as evidence, but the notebook does not block execution.\n",
    "# MAGIC\n",
    "# MAGIC Set `FAIL_ON_ERROR = True` when Bronze ingestion is active and quality checks must block the pipeline.\n",
    "# MAGIC\n",
    "# MAGIC ## Documentation Standard\n",
    "# MAGIC - Python functions and variables are written in English.\n",
    "# MAGIC - Table and field names follow Portuguese mnemonic standards.\n",
    "# MAGIC - Comments and documentation are written in English.\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %run ../99_utils/utils_config\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %run ../99_utils/utils_quality\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "from datetime import datetime\n",
    "from typing import Dict, Any\n",
    "\n",
    "from pyspark.sql import DataFrame\n",
    "from pyspark.sql import functions as F\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "print(\"=\" * 90)\n",
    "print(\"BRAZIL LEGISLATIVE ANALYTICS MEDALLION\")\n",
    "print(\"01 - QUALITY BRONZE CHECKS\")\n",
    "print(\"=\" * 90)\n",
    "print(f\"Execution Timestamp: {datetime.now()}\")\n",
    "print(f\"Catalog: {CATALOG_NAME}\")\n",
    "print(f\"Layer: {SCHEMA_BRONZE}\")\n",
    "print(\"=\" * 90)\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# ============================================================\n",
    "# QUALITY CONFIGURATION\n",
    "# ============================================================\n",
    "\n",
    "NOTEBOOK_NAME = \"01_quality_bronze_checks\"\n",
    "LAYER_NAME = \"bronze\"\n",
    "\n",
    "# During early development, Bronze tables may not exist yet.\n",
    "# Set to True when Bronze ingestion is active and quality checks\n",
    "# must block the pipeline.\n",
    "FAIL_ON_ERROR = False\n",
    "\n",
    "DATA_QUALITY_LOG_TABLE = (\n",
    "    f\"{CATALOG_NAME}.\"\n",
    "    f\"{SCHEMA_AUDIT}.\"\n",
    "    f\"{AUD_TB_LOG_QUALIDADE_DADOS}\"\n",
    ")\n",
    "\n",
    "BRONZE_ENTITY_TABLES = BRONZE_TABLES\n",
    "\n",
    "quality_results = []\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# ============================================================\n",
    "# QUALITY HELPERS\n",
    "# ============================================================\n",
    "\n",
    "def add_quality_result(\n",
    "    rule_name: str,\n",
    "    rule_description: str,\n",
    "    validation_status: str,\n",
    "    total_records: int,\n",
    "    invalid_records: int,\n",
    "    invalid_percentage: float,\n",
    "    message: str,\n",
    "    entity_name: str,\n",
    "    target_table: str,\n",
    ") -> None:\n",
    "    \"\"\"\n",
    "    Adds a quality validation result to the in-memory result list.\n",
    "    \"\"\"\n",
    "\n",
    "    quality_results.append({\n",
    "        \"nome_regra\": rule_name,\n",
    "        \"descricao_regra\": rule_description,\n",
    "        \"status_validacao\": validation_status,\n",
    "        \"total_registros\": int(total_records) if total_records is not None else 0,\n",
    "        \"registros_invalidos\": int(invalid_records) if invalid_records is not None else 0,\n",
    "        \"percentual_invalidos\": float(invalid_percentage) if invalid_percentage is not None else 0.0,\n",
    "        \"mensagem\": message,\n",
    "        \"entity_name\": entity_name,\n",
    "        \"target_table\": target_table,\n",
    "    })\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def add_exception_result(\n",
    "    entity_name: str,\n",
    "    target_table: str,\n",
    "    error: Exception,\n",
    ") -> None:\n",
    "    \"\"\"\n",
    "    Adds a controlled exception result to the quality result list.\n",
    "    \"\"\"\n",
    "\n",
    "    add_quality_result(\n",
    "        rule_name=\"bronze_quality_exception\",\n",
    "        rule_description=\"Captures unexpected errors during Bronze quality validation.\",\n",
    "        validation_status=QUALITY_FAILED,\n",
    "        total_records=1,\n",
    "        invalid_records=1,\n",
    "        invalid_percentage=100.0,\n",
    "        message=f\"Unexpected error during Bronze quality validation: {str(error)}\",\n",
    "        entity_name=entity_name,\n",
    "        target_table=target_table,\n",
    "    )\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def table_exists(\n",
    "    full_table_name: str,\n",
    ") -> bool:\n",
    "    \"\"\"\n",
    "    Checks whether a fully qualified table exists.\n",
    "    \"\"\"\n",
    "\n",
    "    try:\n",
    "        return spark.catalog.tableExists(full_table_name)\n",
    "\n",
    "    except Exception:\n",
    "        return False\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def get_table_dataframe(\n",
    "    full_table_name: str,\n",
    ") -> DataFrame:\n",
    "    \"\"\"\n",
    "    Reads a table into a Spark DataFrame.\n",
    "    \"\"\"\n",
    "\n",
    "    return spark.table(full_table_name)\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def count_records(\n",
    "    dataframe: DataFrame,\n",
    ") -> int:\n",
    "    \"\"\"\n",
    "    Counts records from a Spark DataFrame.\n",
    "    \"\"\"\n",
    "\n",
    "    return dataframe.count()\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def validate_table_exists(\n",
    "    entity_name: str,\n",
    "    full_table_name: str,\n",
    ") -> bool:\n",
    "    \"\"\"\n",
    "    Validates whether a Bronze table exists.\n",
    "    \"\"\"\n",
    "\n",
    "    exists = table_exists(full_table_name)\n",
    "\n",
    "    add_quality_result(\n",
    "        rule_name=\"bronze_table_exists\",\n",
    "        rule_description=\"Validates whether the Bronze table exists.\",\n",
    "        validation_status=QUALITY_PASSED if exists else QUALITY_FAILED,\n",
    "        total_records=1,\n",
    "        invalid_records=0 if exists else 1,\n",
    "        invalid_percentage=0.0 if exists else 100.0,\n",
    "        message=(\n",
    "            \"Bronze table exists.\"\n",
    "            if exists\n",
    "            else \"Bronze table does not exist.\"\n",
    "        ),\n",
    "        entity_name=entity_name,\n",
    "        target_table=full_table_name,\n",
    "    )\n",
    "\n",
    "    return exists\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def validate_minimum_records(\n",
    "    dataframe: DataFrame,\n",
    "    entity_name: str,\n",
    "    full_table_name: str,\n",
    ") -> int:\n",
    "    \"\"\"\n",
    "    Validates whether a Bronze table contains at least one record.\n",
    "    \"\"\"\n",
    "\n",
    "    total_records = count_records(dataframe)\n",
    "    invalid_records = 0 if total_records > 0 else 1\n",
    "\n",
    "    add_quality_result(\n",
    "        rule_name=\"bronze_minimum_records\",\n",
    "        rule_description=\"Validates whether the Bronze table contains at least one record.\",\n",
    "        validation_status=QUALITY_PASSED if total_records > 0 else QUALITY_WARNING,\n",
    "        total_records=total_records,\n",
    "        invalid_records=invalid_records,\n",
    "        invalid_percentage=0.0 if total_records > 0 else 100.0,\n",
    "        message=f\"Bronze table record count: {total_records}\",\n",
    "        entity_name=entity_name,\n",
    "        target_table=full_table_name,\n",
    "    )\n",
    "\n",
    "    return total_records\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def validate_traceability_columns(\n",
    "    dataframe: DataFrame,\n",
    "    entity_name: str,\n",
    "    full_table_name: str,\n",
    ") -> None:\n",
    "    \"\"\"\n",
    "    Validates required Bronze traceability columns.\n",
    "    \"\"\"\n",
    "\n",
    "    result = validate_required_columns(\n",
    "        dataframe=dataframe,\n",
    "        required_columns=BRONZE_REQUIRED_COLUMNS,\n",
    "    )\n",
    "\n",
    "    add_quality_result(\n",
    "        rule_name=\"bronze_required_traceability_columns\",\n",
    "        rule_description=\"Validates required Bronze traceability columns.\",\n",
    "        validation_status=result[\"status_validacao\"],\n",
    "        total_records=result[\"total_registros\"],\n",
    "        invalid_records=result[\"registros_invalidos\"],\n",
    "        invalid_percentage=result[\"percentual_invalidos\"],\n",
    "        message=result[\"mensagem\"],\n",
    "        entity_name=entity_name,\n",
    "        target_table=full_table_name,\n",
    "    )\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def validate_endpoint_traceability(\n",
    "    dataframe: DataFrame,\n",
    "    entity_name: str,\n",
    "    full_table_name: str,\n",
    ") -> None:\n",
    "    \"\"\"\n",
    "    Validates whether source endpoint traceability is populated.\n",
    "    \"\"\"\n",
    "\n",
    "    if \"aud_tx_endpoint_origem\" not in dataframe.columns:\n",
    "\n",
    "        add_quality_result(\n",
    "            rule_name=\"bronze_endpoint_traceability\",\n",
    "            rule_description=\"Validates whether source endpoint traceability is available.\",\n",
    "            validation_status=QUALITY_FAILED,\n",
    "            total_records=1,\n",
    "            invalid_records=1,\n",
    "            invalid_percentage=100.0,\n",
    "            message=\"Column aud_tx_endpoint_origem does not exist.\",\n",
    "            entity_name=entity_name,\n",
    "            target_table=full_table_name,\n",
    "        )\n",
    "\n",
    "        return\n",
    "\n",
    "    total_records = dataframe.count()\n",
    "\n",
    "    invalid_records = (\n",
    "        dataframe\n",
    "        .filter(\n",
    "            F.col(\"aud_tx_endpoint_origem\").isNull()\n",
    "            | (F.trim(F.col(\"aud_tx_endpoint_origem\")) == \"\")\n",
    "        )\n",
    "        .count()\n",
    "    )\n",
    "\n",
    "    invalid_percentage = (\n",
    "        0.0 if total_records == 0\n",
    "        else round((invalid_records / total_records) * 100, 2)\n",
    "    )\n",
    "\n",
    "    validation_status = (\n",
    "        QUALITY_PASSED\n",
    "        if invalid_records == 0\n",
    "        else QUALITY_WARNING\n",
    "    )\n",
    "\n",
    "    add_quality_result(\n",
    "        rule_name=\"bronze_endpoint_traceability\",\n",
    "        rule_description=\"Validates whether source endpoint traceability is populated.\",\n",
    "        validation_status=validation_status,\n",
    "        total_records=total_records,\n",
    "        invalid_records=invalid_records,\n",
    "        invalid_percentage=invalid_percentage,\n",
    "        message=f\"Records without endpoint traceability: {invalid_records}\",\n",
    "        entity_name=entity_name,\n",
    "        target_table=full_table_name,\n",
    "    )\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def validate_hash_duplicates(\n",
    "    dataframe: DataFrame,\n",
    "    entity_name: str,\n",
    "    full_table_name: str,\n",
    ") -> None:\n",
    "    \"\"\"\n",
    "    Validates duplicated records based on the Bronze record hash.\n",
    "    \"\"\"\n",
    "\n",
    "    if \"aud_tx_hash_registro\" not in dataframe.columns:\n",
    "\n",
    "        add_quality_result(\n",
    "            rule_name=\"bronze_hash_duplicate_check\",\n",
    "            rule_description=\"Validates duplicated records based on the Bronze record hash.\",\n",
    "            validation_status=QUALITY_FAILED,\n",
    "            total_records=1,\n",
    "            invalid_records=1,\n",
    "            invalid_percentage=100.0,\n",
    "            message=\"Column aud_tx_hash_registro does not exist.\",\n",
    "            entity_name=entity_name,\n",
    "            target_table=full_table_name,\n",
    "        )\n",
    "\n",
    "        return\n",
    "\n",
    "    result = validate_duplicates(\n",
    "        dataframe=dataframe,\n",
    "        key_columns=[\"aud_tx_hash_registro\"],\n",
    "    )\n",
    "\n",
    "    add_quality_result(\n",
    "        rule_name=\"bronze_hash_duplicate_check\",\n",
    "        rule_description=\"Validates duplicated records based on the Bronze record hash.\",\n",
    "        validation_status=result[\"status_validacao\"],\n",
    "        total_records=result[\"total_registros\"],\n",
    "        invalid_records=result[\"registros_invalidos\"],\n",
    "        invalid_percentage=result[\"percentual_invalidos\"],\n",
    "        message=result[\"mensagem\"],\n",
    "        entity_name=entity_name,\n",
    "        target_table=full_table_name,\n",
    "    )\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def run_entity_checks(\n",
    "    entity_name: str,\n",
    "    table_name: str,\n",
    ") -> None:\n",
    "    \"\"\"\n",
    "    Executes all Bronze quality checks for a single entity.\n",
    "    \"\"\"\n",
    "\n",
    "    full_table_name = get_bronze_table(table_name)\n",
    "\n",
    "    print(\"=\" * 90)\n",
    "    print(f\"Running Bronze quality checks for: {full_table_name}\")\n",
    "    print(\"=\" * 90)\n",
    "\n",
    "    try:\n",
    "\n",
    "        if not validate_table_exists(\n",
    "            entity_name=entity_name,\n",
    "            full_table_name=full_table_name,\n",
    "        ):\n",
    "            return\n",
    "\n",
    "        dataframe = get_table_dataframe(full_table_name)\n",
    "\n",
    "        validate_minimum_records(\n",
    "            dataframe=dataframe,\n",
    "            entity_name=entity_name,\n",
    "            full_table_name=full_table_name,\n",
    "        )\n",
    "\n",
    "        validate_traceability_columns(\n",
    "            dataframe=dataframe,\n",
    "            entity_name=entity_name,\n",
    "            full_table_name=full_table_name,\n",
    "        )\n",
    "\n",
    "        validate_endpoint_traceability(\n",
    "            dataframe=dataframe,\n",
    "            entity_name=entity_name,\n",
    "            full_table_name=full_table_name,\n",
    "        )\n",
    "\n",
    "        validate_hash_duplicates(\n",
    "            dataframe=dataframe,\n",
    "            entity_name=entity_name,\n",
    "            full_table_name=full_table_name,\n",
    "        )\n",
    "\n",
    "    except Exception as error:\n",
    "\n",
    "        add_exception_result(\n",
    "            entity_name=entity_name,\n",
    "            target_table=full_table_name,\n",
    "            error=error,\n",
    "        )\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def build_bronze_quality_log() -> DataFrame:\n",
    "    \"\"\"\n",
    "    Builds the final Bronze quality log DataFrame.\n",
    "    \"\"\"\n",
    "\n",
    "    if not quality_results:\n",
    "\n",
    "        add_quality_result(\n",
    "            rule_name=\"bronze_quality_no_results\",\n",
    "            rule_description=\"Validates whether Bronze quality checks produced results.\",\n",
    "            validation_status=QUALITY_WARNING,\n",
    "            total_records=0,\n",
    "            invalid_records=0,\n",
    "            invalid_percentage=0.0,\n",
    "            message=\"No Bronze quality results were generated.\",\n",
    "            entity_name=\"bronze\",\n",
    "            target_table=DATA_QUALITY_LOG_TABLE,\n",
    "        )\n",
    "\n",
    "    quality_base_df = spark.createDataFrame(\n",
    "        quality_results\n",
    "    )\n",
    "\n",
    "    return (\n",
    "        quality_base_df\n",
    "        .withColumn(\"qlt_id_log\", F.expr(\"uuid()\"))\n",
    "        .withColumn(\"aud_id_execucao\", F.lit(RUN_ID))\n",
    "        .withColumn(\"aud_tx_nome_projeto\", F.lit(PROJECT_NAME))\n",
    "        .withColumn(\"aud_tx_versao_pipeline\", F.lit(PROJECT_VERSION))\n",
    "        .withColumn(\"aud_tx_ambiente\", F.lit(PROJECT_ENVIRONMENT))\n",
    "        .withColumn(\"aud_tx_nome_notebook\", F.lit(NOTEBOOK_NAME))\n",
    "        .withColumn(\"aud_tx_nome_camada\", F.lit(LAYER_NAME))\n",
    "        .withColumn(\"aud_tx_nome_entidade\", F.col(\"entity_name\"))\n",
    "        .withColumn(\"aud_tx_tabela_destino\", F.col(\"target_table\"))\n",
    "        .withColumn(\"qlt_tx_nome_regra\", F.col(\"nome_regra\"))\n",
    "        .withColumn(\"qlt_tx_descricao_regra\", F.col(\"descricao_regra\"))\n",
    "        .withColumn(\"qlt_tx_status_validacao\", F.col(\"status_validacao\"))\n",
    "        .withColumn(\"qlt_qt_total_registros\", F.col(\"total_registros\"))\n",
    "        .withColumn(\"qlt_qt_registros_invalidos\", F.col(\"registros_invalidos\"))\n",
    "        .withColumn(\"qlt_pc_registros_invalidos\", F.col(\"percentual_invalidos\"))\n",
    "        .withColumn(\"qlt_dh_validacao\", F.current_timestamp())\n",
    "        .withColumn(\"qlt_tx_mensagem\", F.col(\"mensagem\"))\n",
    "        .select(\n",
    "            \"qlt_id_log\",\n",
    "            \"aud_id_execucao\",\n",
    "            \"aud_tx_nome_projeto\",\n",
    "            \"aud_tx_versao_pipeline\",\n",
    "            \"aud_tx_ambiente\",\n",
    "            \"aud_tx_nome_notebook\",\n",
    "            \"aud_tx_nome_camada\",\n",
    "            \"aud_tx_nome_entidade\",\n",
    "            \"aud_tx_tabela_destino\",\n",
    "            \"qlt_tx_nome_regra\",\n",
    "            \"qlt_tx_descricao_regra\",\n",
    "            \"qlt_tx_status_validacao\",\n",
    "            \"qlt_qt_total_registros\",\n",
    "            \"qlt_qt_registros_invalidos\",\n",
    "            \"qlt_pc_registros_invalidos\",\n",
    "            \"qlt_dh_validacao\",\n",
    "            \"qlt_tx_mensagem\",\n",
    "        )\n",
    "    )\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %md\n",
    "# MAGIC ## 1. Execute Bronze Quality Checks\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "for entity_name, table_name in BRONZE_ENTITY_TABLES.items():\n",
    "\n",
    "    run_entity_checks(\n",
    "        entity_name=entity_name,\n",
    "        table_name=table_name,\n",
    "    )\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %md\n",
    "# MAGIC ## 2. Persist Quality Results\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "quality_log_df = build_bronze_quality_log()\n",
    "\n",
    "quality_log_df.write.mode(\n",
    "    \"append\"\n",
    ").saveAsTable(DATA_QUALITY_LOG_TABLE)\n",
    "\n",
    "print(\n",
    "    f\"Bronze quality results persisted into: \"\n",
    "    f\"{DATA_QUALITY_LOG_TABLE}\"\n",
    ")\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %md\n",
    "# MAGIC ## 3. Display Quality Results\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "display(quality_log_df)\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %md\n",
    "# MAGIC ## 4. Quality Summary\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "failed_count = (\n",
    "    quality_log_df\n",
    "    .filter(\"qlt_tx_status_validacao = 'FAILED'\")\n",
    "    .count()\n",
    ")\n",
    "\n",
    "warning_count = (\n",
    "    quality_log_df\n",
    "    .filter(\"qlt_tx_status_validacao = 'WARNING'\")\n",
    "    .count()\n",
    ")\n",
    "\n",
    "passed_count = (\n",
    "    quality_log_df\n",
    "    .filter(\"qlt_tx_status_validacao = 'PASSED'\")\n",
    "    .count()\n",
    ")\n",
    "\n",
    "print(\"=\" * 90)\n",
    "print(\"BRONZE QUALITY SUMMARY\")\n",
    "print(\"=\" * 90)\n",
    "print(f\"Passed validations: {passed_count}\")\n",
    "print(f\"Warning validations: {warning_count}\")\n",
    "print(f\"Failed validations: {failed_count}\")\n",
    "print(\"=\" * 90)\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# ============================================================\n",
    "# QUALITY EXECUTION POLICY\n",
    "# ============================================================\n",
    "\n",
    "if failed_count > 0 and FAIL_ON_ERROR:\n",
    "\n",
    "    raise Exception(\n",
    "        f\"Bronze quality validation failed with \"\n",
    "        f\"{failed_count} failed validation(s).\"\n",
    "    )\n",
    "\n",
    "if failed_count > 0:\n",
    "\n",
    "    print(\n",
    "        f\"WARNING: Bronze quality validation finished with \"\n",
    "        f\"{failed_count} failed validation(s). \"\n",
    "        \"This is expected if Bronze tables have not been created yet.\"\n",
    "    )\n",
    "\n",
    "print(\"BRONZE QUALITY CHECKS COMPLETED\")"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "01_quality_bronze_checks",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}