{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "9dff7d1c-6d39-4169-8320-6622b95148d9",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# LOAD GLOBAL PROJECT CONFIGURATION\n",
    "# ============================================================\n",
    "\n",
    "# Loads reusable constants, API parameters,\n",
    "# naming conventions and audit configuration\n",
    "# shared across the project.\n",
    "\n",
    "# MAGIC %run ./utils_config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "07caa689-c1a8-45e9-8e86-afc0c20115a8",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PROJECT CONFIGURATION LOADED SUCCESSFULLY\nPROJECT_NAME: brazil_legislative_analytics\nPROJECT_VERSION: v1.0.0\nPROJECT_ENVIRONMENT: dev\nCATALOG_NAME: brazil_legislative_analytics\nRUN_ID: a926ff8a-70f4-467e-a2a3-77be77328083\n"
     ]
    }
   ],
   "source": [
    "%run ./utils_config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "4ee7808c-8391-4d61-a41a-eccfcd8938bb",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "utils_api_client loaded successfully.\n"
     ]
    },
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "utils_config loaded successfully.\n"
     ]
    }
   ],
   "source": [
    "# Databricks notebook source\n",
    "# MAGIC %md\n",
    "# MAGIC # 99 Utils — Câmara API Client\n",
    "# MAGIC\n",
    "# MAGIC **Notebook:** `utils_api_client`\n",
    "# MAGIC\n",
    "# MAGIC Provides reusable functions to request data from the Câmara dos Deputados Open Data API.\n",
    "# MAGIC\n",
    "# MAGIC This notebook centralizes API access logic used by Bronze ingestion notebooks.\n",
    "# MAGIC\n",
    "# MAGIC ## Responsibilities\n",
    "# MAGIC\n",
    "# MAGIC - Execute HTTP GET requests against Câmara Open Data API\n",
    "# MAGIC - Apply timeout and retry strategy\n",
    "# MAGIC - Standardize API response handling\n",
    "# MAGIC - Support resilient Bronze ingestion\n",
    "# MAGIC - Preserve error details for auditability\n",
    "# MAGIC\n",
    "# MAGIC ## Naming Standard\n",
    "# MAGIC\n",
    "# MAGIC - Table and field names use Portuguese mnemonics.\n",
    "# MAGIC - Comments and documentation are written in English.\n",
    "# MAGIC - Utility functions use descriptive English names for reuse and readability.\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "import time\n",
    "import requests\n",
    "\n",
    "from typing import (\n",
    "    Optional,\n",
    "    Dict,\n",
    "    Any,\n",
    "    List,\n",
    ")\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %run ./utils_config\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# ============================================================\n",
    "# API CLIENT CONFIGURATION\n",
    "# ============================================================\n",
    "\n",
    "DEFAULT_REQUEST_HEADERS = {\n",
    "    \"Accept\": \"application/json\",\n",
    "    \"User-Agent\": (\n",
    "        \"brazil-legislative-analytics/\"\n",
    "        f\"{PROJECT_VERSION}\"\n",
    "    ),\n",
    "}\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def build_request_url(\n",
    "    endpoint_path: str,\n",
    ") -> str:\n",
    "    \"\"\"\n",
    "    Builds the full Câmara API request URL.\n",
    "    \"\"\"\n",
    "\n",
    "    if endpoint_path is None:\n",
    "        raise ValueError(\n",
    "            \"Endpoint path cannot be None.\"\n",
    "        )\n",
    "\n",
    "    normalized_endpoint = (\n",
    "        str(endpoint_path)\n",
    "        .strip()\n",
    "    )\n",
    "\n",
    "    if normalized_endpoint == \"\":\n",
    "        raise ValueError(\n",
    "            \"Endpoint path cannot be empty.\"\n",
    "        )\n",
    "\n",
    "    if not normalized_endpoint.startswith(\"/\"):\n",
    "        normalized_endpoint = (\n",
    "            f\"/{normalized_endpoint}\"\n",
    "        )\n",
    "\n",
    "    return (\n",
    "        f\"{CAMARA_API_BASE_URL}\"\n",
    "        f\"{normalized_endpoint}\"\n",
    "    )\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def parse_json_response(\n",
    "    api_response: requests.Response,\n",
    "    endpoint_path: str,\n",
    ") -> Dict[str, Any]:\n",
    "    \"\"\"\n",
    "    Parses an HTTP response as JSON.\n",
    "    \"\"\"\n",
    "\n",
    "    try:\n",
    "        parsed_response = (\n",
    "            api_response.json()\n",
    "        )\n",
    "\n",
    "    except Exception as error:\n",
    "\n",
    "        raise ValueError(\n",
    "            f\"Failed to parse API response as JSON \"\n",
    "            f\"| endpoint={endpoint_path} \"\n",
    "            f\"| status_code={api_response.status_code} \"\n",
    "            f\"| error={str(error)}\"\n",
    "        )\n",
    "\n",
    "    if not isinstance(parsed_response, dict):\n",
    "\n",
    "        raise ValueError(\n",
    "            f\"API response is not a dictionary \"\n",
    "            f\"| endpoint={endpoint_path}\"\n",
    "        )\n",
    "\n",
    "    return parsed_response\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def fetch_camara_api_data(\n",
    "    endpoint_path: str,\n",
    "    query_params: Optional[Dict[str, Any]] = None,\n",
    "    request_timeout_seconds: int = API_REQUEST_TIMEOUT_SECONDS,\n",
    "    max_retry_attempts: int = API_MAX_RETRY_ATTEMPTS,\n",
    "    retry_sleep_seconds: int = API_RETRY_SLEEP_SECONDS,\n",
    "    request_headers: Optional[Dict[str, str]] = None,\n",
    ") -> Dict[str, Any]:\n",
    "    \"\"\"\n",
    "    Requests data from a Câmara dos Deputados Open Data API endpoint.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    endpoint_path : str\n",
    "        API endpoint path, for example: \"/deputados\".\n",
    "\n",
    "    query_params : dict, optional\n",
    "        Query parameters sent to the API request.\n",
    "\n",
    "    request_timeout_seconds : int\n",
    "        Maximum request timeout in seconds.\n",
    "\n",
    "    max_retry_attempts : int\n",
    "        Maximum number of retry attempts.\n",
    "\n",
    "    retry_sleep_seconds : int\n",
    "        Waiting time between retry attempts.\n",
    "\n",
    "    request_headers : dict, optional\n",
    "        Additional request headers.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    dict\n",
    "        JSON response returned by the API.\n",
    "\n",
    "    Raises\n",
    "    ------\n",
    "    RuntimeError\n",
    "        Raised when all retry attempts fail.\n",
    "    \"\"\"\n",
    "\n",
    "    request_url = build_request_url(\n",
    "        endpoint_path=endpoint_path,\n",
    "    )\n",
    "\n",
    "    headers = (\n",
    "        request_headers\n",
    "        or DEFAULT_REQUEST_HEADERS\n",
    "    )\n",
    "\n",
    "    last_error = None\n",
    "\n",
    "    for attempt_number in range(\n",
    "        1,\n",
    "        max_retry_attempts + 1,\n",
    "    ):\n",
    "\n",
    "        try:\n",
    "\n",
    "            api_response = requests.get(\n",
    "                request_url,\n",
    "                params=query_params,\n",
    "                timeout=request_timeout_seconds,\n",
    "                headers=headers,\n",
    "            )\n",
    "\n",
    "            api_response.raise_for_status()\n",
    "\n",
    "            return parse_json_response(\n",
    "                api_response=api_response,\n",
    "                endpoint_path=endpoint_path,\n",
    "            )\n",
    "\n",
    "        except requests.exceptions.Timeout as error:\n",
    "\n",
    "            last_error = error\n",
    "            error_type = \"timeout\"\n",
    "\n",
    "        except requests.exceptions.HTTPError as error:\n",
    "\n",
    "            last_error = error\n",
    "\n",
    "            status_code = (\n",
    "                error.response.status_code\n",
    "                if error.response is not None\n",
    "                else \"unknown\"\n",
    "            )\n",
    "\n",
    "            error_type = (\n",
    "                f\"http_error_{status_code}\"\n",
    "            )\n",
    "\n",
    "        except requests.exceptions.RequestException as error:\n",
    "\n",
    "            last_error = error\n",
    "            error_type = \"request_error\"\n",
    "\n",
    "        except Exception as error:\n",
    "\n",
    "            last_error = error\n",
    "            error_type = \"unexpected_error\"\n",
    "\n",
    "        print(\n",
    "            f\"[WARNING] API request failed \"\n",
    "            f\"| endpoint={endpoint_path} \"\n",
    "            f\"| attempt={attempt_number}/{max_retry_attempts} \"\n",
    "            f\"| error_type={error_type} \"\n",
    "            f\"| error={str(last_error)}\"\n",
    "        )\n",
    "\n",
    "        if (\n",
    "            attempt_number\n",
    "            < max_retry_attempts\n",
    "        ):\n",
    "\n",
    "            time.sleep(\n",
    "                retry_sleep_seconds\n",
    "                * attempt_number\n",
    "            )\n",
    "\n",
    "    raise RuntimeError(\n",
    "        f\"API request failed after \"\n",
    "        f\"{max_retry_attempts} attempt(s) \"\n",
    "        f\"| endpoint={endpoint_path} \"\n",
    "        f\"| params={query_params} \"\n",
    "        f\"| last_error={str(last_error)}\"\n",
    "    )\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def extract_response_records(\n",
    "    api_response: Dict[str, Any],\n",
    "    data_field_name: str = API_RESPONSE_DATA_FIELD,\n",
    ") -> List[Dict[str, Any]]:\n",
    "    \"\"\"\n",
    "    Extracts the data records list from a Câmara API JSON response.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    api_response : dict\n",
    "        Full API JSON response.\n",
    "\n",
    "    data_field_name : str\n",
    "        Field name that contains the data records.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    list\n",
    "        List of records found in the API response.\n",
    "    \"\"\"\n",
    "\n",
    "    if api_response is None:\n",
    "        return []\n",
    "\n",
    "    if not isinstance(api_response, dict):\n",
    "        return []\n",
    "\n",
    "    records = api_response.get(\n",
    "        data_field_name,\n",
    "        [],\n",
    "    )\n",
    "\n",
    "    if records is None:\n",
    "        return []\n",
    "\n",
    "    if not isinstance(records, list):\n",
    "        return []\n",
    "\n",
    "    return records\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def check_endpoint_availability(\n",
    "    endpoint_path: str,\n",
    "    query_params: Optional[Dict[str, Any]] = None,\n",
    "    request_timeout_seconds: int = 15,\n",
    "    fail_silently: bool = True,\n",
    ") -> bool:\n",
    "    \"\"\"\n",
    "    Checks whether an API endpoint is available.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    endpoint_path : str\n",
    "        API endpoint path.\n",
    "\n",
    "    query_params : dict, optional\n",
    "        Query parameters sent to the API request.\n",
    "\n",
    "    request_timeout_seconds : int\n",
    "        Maximum timeout used for the availability check.\n",
    "\n",
    "    fail_silently : bool\n",
    "        When True, returns False instead of raising exceptions.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    bool\n",
    "        True when the endpoint returns a valid response,\n",
    "        otherwise False.\n",
    "    \"\"\"\n",
    "\n",
    "    try:\n",
    "\n",
    "        fetch_camara_api_data(\n",
    "            endpoint_path=endpoint_path,\n",
    "            query_params=query_params,\n",
    "            request_timeout_seconds=request_timeout_seconds,\n",
    "            max_retry_attempts=1,\n",
    "        )\n",
    "\n",
    "        return True\n",
    "\n",
    "    except Exception as error:\n",
    "\n",
    "        if not fail_silently:\n",
    "            raise error\n",
    "\n",
    "        print(\n",
    "            f\"[WARNING] Endpoint availability check failed \"\n",
    "            f\"| endpoint={endpoint_path} \"\n",
    "            f\"| error={str(error)}\"\n",
    "        )\n",
    "\n",
    "        return False\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "print(\"utils_api_client loaded successfully.\")"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "utils_api_client",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}