{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "557e8d51-e6d0-467c-83ab-5c369db4d2c2",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Project configuration loaded successfully.\nProject: brazil_legislative_analytics\nCatalog: brazil_legislative_analytics\nEnvironment: dev\nDefault legislatures: [56, 57]\nAnalysis years: [2022, 2023, 2024, 2025, 2026]\n"
     ]
    }
   ],
   "source": [
    "%run ./utils_config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "7dbf7390-3d28-4745-896e-47dcb9001fa1",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "utils_quality loaded successfully.\n"
     ]
    }
   ],
   "source": [
    "# Databricks notebook source\n",
    "# MAGIC %md\n",
    "# MAGIC # 99 Utils — Data Quality Utilities\n",
    "# MAGIC\n",
    "# MAGIC **Notebook:** `utils_quality`\n",
    "# MAGIC\n",
    "# MAGIC Provides reusable data quality functions used across Bronze, Silver, Gold, Marts and Quality notebooks.\n",
    "# MAGIC\n",
    "# MAGIC ## Responsibilities\n",
    "# MAGIC - Validate required columns\n",
    "# MAGIC - Validate null values\n",
    "# MAGIC - Validate duplicate keys\n",
    "# MAGIC - Validate allowed domain values\n",
    "# MAGIC - Calculate invalid record percentages\n",
    "# MAGIC - Support quality logging into audit tables\n",
    "# MAGIC\n",
    "# MAGIC ## Technical Notes\n",
    "# MAGIC - Python functions and variables are written in English.\n",
    "# MAGIC - Table and field names follow Portuguese mnemonic standards.\n",
    "# MAGIC - Comments and documentation are written in English.\n",
    "# MAGIC - Validation functions return structured dictionaries or DataFrames for auditability.\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %run ./utils_config\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "from typing import List, Dict, Any\n",
    "from pyspark.sql import DataFrame\n",
    "from pyspark.sql import functions as F\n",
    "from pyspark.sql.types import LongType, DoubleType\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "QUALITY_PASSED = \"PASSED\"\n",
    "QUALITY_FAILED = \"FAILED\"\n",
    "QUALITY_WARNING = \"WARNING\"\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def validate_dataframe(dataframe: DataFrame) -> None:\n",
    "    \"\"\"\n",
    "    Validates whether the input object is a Spark DataFrame.\n",
    "    \"\"\"\n",
    "\n",
    "    if dataframe is None:\n",
    "        raise ValueError(\"Input DataFrame cannot be None for data quality validation.\")\n",
    "\n",
    "    if not hasattr(dataframe, \"columns\"):\n",
    "        raise TypeError(\"Input object must be a Spark DataFrame.\")\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def validate_required_columns(\n",
    "    dataframe: DataFrame,\n",
    "    required_columns: List[str],\n",
    ") -> Dict[str, Any]:\n",
    "    \"\"\"\n",
    "    Validates whether required columns exist in a DataFrame.\n",
    "    \"\"\"\n",
    "\n",
    "    validate_dataframe(dataframe)\n",
    "\n",
    "    required_columns = required_columns or []\n",
    "\n",
    "    missing_columns = [\n",
    "        column\n",
    "        for column in required_columns\n",
    "        if column not in dataframe.columns\n",
    "    ]\n",
    "\n",
    "    validation_status = (\n",
    "        QUALITY_PASSED\n",
    "        if len(missing_columns) == 0\n",
    "        else QUALITY_FAILED\n",
    "    )\n",
    "\n",
    "    return {\n",
    "        \"nome_regra\": \"required_columns_check\",\n",
    "        \"descricao_regra\": \"Validates whether all required columns exist in the DataFrame.\",\n",
    "        \"status_validacao\": validation_status,\n",
    "        \"total_registros\": len(required_columns),\n",
    "        \"registros_invalidos\": len(missing_columns),\n",
    "        \"percentual_invalidos\": (\n",
    "            0.0 if len(required_columns) == 0\n",
    "            else round((len(missing_columns) / len(required_columns)) * 100, 2)\n",
    "        ),\n",
    "        \"mensagem\": f\"Missing columns: {missing_columns}\",\n",
    "    }\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def validate_nulls(\n",
    "    dataframe: DataFrame,\n",
    "    columns: List[str],\n",
    ") -> List[Dict[str, Any]]:\n",
    "    \"\"\"\n",
    "    Validates null values for selected columns.\n",
    "    \"\"\"\n",
    "\n",
    "    validate_dataframe(dataframe)\n",
    "\n",
    "    results = []\n",
    "    total_records = dataframe.count()\n",
    "\n",
    "    for column in columns:\n",
    "\n",
    "        if column not in dataframe.columns:\n",
    "            results.append({\n",
    "                \"nome_regra\": f\"null_check_{column}\",\n",
    "                \"descricao_regra\": f\"Validates null values for column {column}.\",\n",
    "                \"status_validacao\": QUALITY_FAILED,\n",
    "                \"total_registros\": total_records,\n",
    "                \"registros_invalidos\": total_records,\n",
    "                \"percentual_invalidos\": 100.0,\n",
    "                \"mensagem\": f\"Column does not exist: {column}\",\n",
    "            })\n",
    "            continue\n",
    "\n",
    "        null_count = dataframe.filter(F.col(column).isNull()).count()\n",
    "\n",
    "        null_percentage = (\n",
    "            0.0 if total_records == 0\n",
    "            else round((null_count / total_records) * 100, 2)\n",
    "        )\n",
    "\n",
    "        validation_status = (\n",
    "            QUALITY_PASSED\n",
    "            if null_count == 0\n",
    "            else QUALITY_WARNING\n",
    "        )\n",
    "\n",
    "        results.append({\n",
    "            \"nome_regra\": f\"null_check_{column}\",\n",
    "            \"descricao_regra\": f\"Validates null values for column {column}.\",\n",
    "            \"status_validacao\": validation_status,\n",
    "            \"total_registros\": total_records,\n",
    "            \"registros_invalidos\": null_count,\n",
    "            \"percentual_invalidos\": null_percentage,\n",
    "            \"mensagem\": f\"Null records found: {null_count}\",\n",
    "        })\n",
    "\n",
    "    return results\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def validate_duplicates(\n",
    "    dataframe: DataFrame,\n",
    "    key_columns: List[str],\n",
    ") -> Dict[str, Any]:\n",
    "    \"\"\"\n",
    "    Validates duplicate records based on business key columns.\n",
    "    \"\"\"\n",
    "\n",
    "    validate_dataframe(dataframe)\n",
    "\n",
    "    missing_columns = [\n",
    "        column\n",
    "        for column in key_columns\n",
    "        if column not in dataframe.columns\n",
    "    ]\n",
    "\n",
    "    total_records = dataframe.count()\n",
    "\n",
    "    if missing_columns:\n",
    "        return {\n",
    "            \"nome_regra\": \"duplicate_key_check\",\n",
    "            \"descricao_regra\": \"Validates duplicated records based on business key columns.\",\n",
    "            \"status_validacao\": QUALITY_FAILED,\n",
    "            \"total_registros\": total_records,\n",
    "            \"registros_invalidos\": total_records,\n",
    "            \"percentual_invalidos\": 100.0,\n",
    "            \"mensagem\": f\"Missing key columns: {missing_columns}\",\n",
    "        }\n",
    "\n",
    "    duplicate_groups = (\n",
    "        dataframe\n",
    "        .groupBy(*key_columns)\n",
    "        .count()\n",
    "        .filter(F.col(\"count\") > 1)\n",
    "        .count()\n",
    "    )\n",
    "\n",
    "    duplicate_percentage = (\n",
    "        0.0 if total_records == 0\n",
    "        else round((duplicate_groups / total_records) * 100, 2)\n",
    "    )\n",
    "\n",
    "    validation_status = (\n",
    "        QUALITY_PASSED\n",
    "        if duplicate_groups == 0\n",
    "        else QUALITY_FAILED\n",
    "    )\n",
    "\n",
    "    return {\n",
    "        \"nome_regra\": \"duplicate_key_check\",\n",
    "        \"descricao_regra\": \"Validates duplicated records based on business key columns.\",\n",
    "        \"status_validacao\": validation_status,\n",
    "        \"total_registros\": total_records,\n",
    "        \"registros_invalidos\": duplicate_groups,\n",
    "        \"percentual_invalidos\": duplicate_percentage,\n",
    "        \"mensagem\": f\"Duplicated key groups found: {duplicate_groups}\",\n",
    "    }\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def validate_domain(\n",
    "    dataframe: DataFrame,\n",
    "    column: str,\n",
    "    allowed_values: List[str],\n",
    ") -> Dict[str, Any]:\n",
    "    \"\"\"\n",
    "    Validates whether a column contains only allowed domain values.\n",
    "    \"\"\"\n",
    "\n",
    "    validate_dataframe(dataframe)\n",
    "\n",
    "    total_records = dataframe.count()\n",
    "\n",
    "    if column not in dataframe.columns:\n",
    "        return {\n",
    "            \"nome_regra\": f\"domain_check_{column}\",\n",
    "            \"descricao_regra\": f\"Validates allowed values for column {column}.\",\n",
    "            \"status_validacao\": QUALITY_FAILED,\n",
    "            \"total_registros\": total_records,\n",
    "            \"registros_invalidos\": total_records,\n",
    "            \"percentual_invalidos\": 100.0,\n",
    "            \"mensagem\": f\"Column does not exist: {column}\",\n",
    "        }\n",
    "\n",
    "    invalid_count = (\n",
    "        dataframe\n",
    "        .filter(~F.col(column).isin(allowed_values))\n",
    "        .count()\n",
    "    )\n",
    "\n",
    "    invalid_percentage = (\n",
    "        0.0 if total_records == 0\n",
    "        else round((invalid_count / total_records) * 100, 2)\n",
    "    )\n",
    "\n",
    "    validation_status = (\n",
    "        QUALITY_PASSED\n",
    "        if invalid_count == 0\n",
    "        else QUALITY_WARNING\n",
    "    )\n",
    "\n",
    "    return {\n",
    "        \"nome_regra\": f\"domain_check_{column}\",\n",
    "        \"descricao_regra\": f\"Validates allowed values for column {column}.\",\n",
    "        \"status_validacao\": validation_status,\n",
    "        \"total_registros\": total_records,\n",
    "        \"registros_invalidos\": invalid_count,\n",
    "        \"percentual_invalidos\": invalid_percentage,\n",
    "        \"mensagem\": f\"Invalid values found: {invalid_count}\",\n",
    "    }\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def build_quality_log(\n",
    "    quality_results: List[Dict[str, Any]],\n",
    "    execution_id: str,\n",
    "    notebook_name: str,\n",
    "    layer_name: str,\n",
    "    entity_name: str,\n",
    "    target_table: str,\n",
    ") -> DataFrame:\n",
    "    \"\"\"\n",
    "    Converts quality validation dictionaries into the audit quality log table format.\n",
    "    \"\"\"\n",
    "\n",
    "    results_df = spark.createDataFrame(quality_results)\n",
    "\n",
    "    return (\n",
    "        results_df\n",
    "        .withColumn(\"qlt_id_log\", F.expr(\"uuid()\"))\n",
    "        .withColumn(\"aud_id_execucao\", F.lit(execution_id))\n",
    "        .withColumn(\"aud_tx_nome_projeto\", F.lit(PROJECT_NAME))\n",
    "        .withColumn(\"aud_tx_versao_pipeline\", F.lit(PIPELINE_VERSION))\n",
    "        .withColumn(\"aud_tx_ambiente\", F.lit(PROJECT_ENVIRONMENT))\n",
    "        .withColumn(\"aud_tx_nome_notebook\", F.lit(notebook_name))\n",
    "        .withColumn(\"aud_tx_nome_camada\", F.lit(layer_name))\n",
    "        .withColumn(\"aud_tx_nome_entidade\", F.lit(entity_name))\n",
    "        .withColumn(\"aud_tx_tabela_destino\", F.lit(target_table))\n",
    "        .withColumn(\"qlt_tx_nome_regra\", F.col(\"nome_regra\"))\n",
    "        .withColumn(\"qlt_tx_descricao_regra\", F.col(\"descricao_regra\"))\n",
    "        .withColumn(\"qlt_tx_status_validacao\", F.col(\"status_validacao\"))\n",
    "        .withColumn(\"qlt_qt_total_registros\", F.col(\"total_registros\").cast(LongType()))\n",
    "        .withColumn(\"qlt_qt_registros_invalidos\", F.col(\"registros_invalidos\").cast(LongType()))\n",
    "        .withColumn(\"qlt_pc_registros_invalidos\", F.col(\"percentual_invalidos\").cast(DoubleType()))\n",
    "        .withColumn(\"qlt_dh_validacao\", F.current_timestamp())\n",
    "        .withColumn(\"qlt_tx_mensagem\", F.col(\"mensagem\"))\n",
    "        .select(\n",
    "            \"qlt_id_log\",\n",
    "            \"aud_id_execucao\",\n",
    "            \"aud_tx_nome_projeto\",\n",
    "            \"aud_tx_versao_pipeline\",\n",
    "            \"aud_tx_ambiente\",\n",
    "            \"aud_tx_nome_notebook\",\n",
    "            \"aud_tx_nome_camada\",\n",
    "            \"aud_tx_nome_entidade\",\n",
    "            \"aud_tx_tabela_destino\",\n",
    "            \"qlt_tx_nome_regra\",\n",
    "            \"qlt_tx_descricao_regra\",\n",
    "            \"qlt_tx_status_validacao\",\n",
    "            \"qlt_qt_total_registros\",\n",
    "            \"qlt_qt_registros_invalidos\",\n",
    "            \"qlt_pc_registros_invalidos\",\n",
    "            \"qlt_dh_validacao\",\n",
    "            \"qlt_tx_mensagem\",\n",
    "        )\n",
    "    )\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def write_quality_log(\n",
    "    quality_dataframe: DataFrame,\n",
    ") -> None:\n",
    "    \"\"\"\n",
    "    Appends quality validation results into the audit quality log table.\n",
    "    \"\"\"\n",
    "\n",
    "    quality_log_table = (\n",
    "        f\"{CATALOG_NAME}.{SCHEMA_AUDIT}.{AUD_TB_LOG_QUALIDADE_DADOS}\"\n",
    "    )\n",
    "\n",
    "    quality_dataframe.write.mode(\"append\").saveAsTable(\n",
    "        quality_log_table\n",
    "    )\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "print(\"utils_quality loaded successfully.\")"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "utils_quality",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}