{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "ed4d04ff-4bb8-4a18-ab53-205c837b1f85",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Project configuration loaded successfully.\nProject: brazil_legislative_analytics\nCatalog: brazil_legislative_analytics\nEnvironment: dev\nDefault legislatures: [56, 57]\nAnalysis years: [2022, 2023, 2024, 2025, 2026]\n"
     ]
    }
   ],
   "source": [
    "%run ./utils_config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "78bc4852-0bd5-4df4-8afd-905e8a90bc62",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "utils_legislature loaded successfully.\n"
     ]
    }
   ],
   "source": [
    "# Databricks notebook source\n",
    "# MAGIC %md\n",
    "# MAGIC # 99 Utils — Legislative Utilities\n",
    "# MAGIC\n",
    "# MAGIC **Notebook:** `utils_legislature`\n",
    "# MAGIC\n",
    "# MAGIC Provides reusable helper functions for legislative periods, party acronyms, Brazilian states and Câmara dos Deputados domain standardization.\n",
    "# MAGIC\n",
    "# MAGIC ## Responsibilities\n",
    "# MAGIC - Normalize party acronyms\n",
    "# MAGIC - Normalize Brazilian state acronyms\n",
    "# MAGIC - Validate legislature identifiers\n",
    "# MAGIC - Map years to legislative periods\n",
    "# MAGIC - Support Bronze, Silver, Gold and Marts transformations\n",
    "# MAGIC\n",
    "# MAGIC ## Technical Notes\n",
    "# MAGIC - Python functions and variables are written in English.\n",
    "# MAGIC - Table and field names follow Portuguese mnemonic standards.\n",
    "# MAGIC - Comments and documentation are written in English.\n",
    "# MAGIC - This notebook does not persist data.\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %run ./utils_config\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "from typing import Optional, Dict, List\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# ============================================================\n",
    "# LEGISLATURE PERIODS\n",
    "# ============================================================\n",
    "\n",
    "LEGISLATURE_PERIODS = {\n",
    "    56: {\n",
    "        \"start_year\": 2019,\n",
    "        \"end_year\": 2023,\n",
    "        \"description\": \"56th Legislature - 2019 to 2023\",\n",
    "    },\n",
    "    57: {\n",
    "        \"start_year\": 2023,\n",
    "        \"end_year\": 2027,\n",
    "        \"description\": \"57th Legislature - 2023 to 2027\",\n",
    "    },\n",
    "}\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# ============================================================\n",
    "# BRAZILIAN STATE ACRONYMS\n",
    "# ============================================================\n",
    "\n",
    "VALID_STATE_ACRONYMS = [\n",
    "    \"AC\", \"AL\", \"AP\", \"AM\", \"BA\", \"CE\", \"DF\",\n",
    "    \"ES\", \"GO\", \"MA\", \"MT\", \"MS\", \"MG\", \"PA\",\n",
    "    \"PB\", \"PR\", \"PE\", \"PI\", \"RJ\", \"RN\", \"RS\",\n",
    "    \"RO\", \"RR\", \"SC\", \"SP\", \"SE\", \"TO\",\n",
    "]\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# ============================================================\n",
    "# COMMON PARTY ACRONYMS\n",
    "# ============================================================\n",
    "\n",
    "VALID_PARTY_ACRONYMS = [\n",
    "    \"AGIR\",\n",
    "    \"AVANTE\",\n",
    "    \"CIDADANIA\",\n",
    "    \"DC\",\n",
    "    \"MDB\",\n",
    "    \"NOVO\",\n",
    "    \"PCDOB\",\n",
    "    \"PDT\",\n",
    "    \"PL\",\n",
    "    \"PMB\",\n",
    "    \"PODE\",\n",
    "    \"PP\",\n",
    "    \"PRD\",\n",
    "    \"PRTB\",\n",
    "    \"PSB\",\n",
    "    \"PSC\",\n",
    "    \"PSD\",\n",
    "    \"PSDB\",\n",
    "    \"PSOL\",\n",
    "    \"PSTU\",\n",
    "    \"PT\",\n",
    "    \"PV\",\n",
    "    \"REDE\",\n",
    "    \"REPUBLICANOS\",\n",
    "    \"SOLIDARIEDADE\",\n",
    "    \"UNIÃO\",\n",
    "    \"UP\",\n",
    "]\n",
    "\n",
    "PARTY_NORMALIZATION_MAP = {\n",
    "    \"UNIAO\": \"UNIÃO\",\n",
    "    \"UNIÃO BRASIL\": \"UNIÃO\",\n",
    "    \"UNIAO BRASIL\": \"UNIÃO\",\n",
    "    \"PC DO B\": \"PCDOB\",\n",
    "    \"PCdoB\": \"PCDOB\",\n",
    "    \"REPUBLICANO\": \"REPUBLICANOS\",\n",
    "}\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def normalize_text(value: Optional[str]) -> Optional[str]:\n",
    "    \"\"\"\n",
    "    Normalizes a text value by trimming spaces and converting it to uppercase.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    value : str, optional\n",
    "        Input text value.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    str or None\n",
    "        Normalized text value.\n",
    "    \"\"\"\n",
    "\n",
    "    if value is None:\n",
    "        return None\n",
    "\n",
    "    normalized_value = str(value).strip()\n",
    "\n",
    "    if normalized_value == \"\":\n",
    "        return None\n",
    "\n",
    "    return normalized_value.upper()\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def normalize_state(value: Optional[str]) -> Optional[str]:\n",
    "    \"\"\"\n",
    "    Normalizes and validates a Brazilian state acronym.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    value : str, optional\n",
    "        State acronym.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    str or None\n",
    "        Normalized state acronym when valid, otherwise None.\n",
    "    \"\"\"\n",
    "\n",
    "    normalized_value = normalize_text(value)\n",
    "\n",
    "    if normalized_value in VALID_STATE_ACRONYMS:\n",
    "        return normalized_value\n",
    "\n",
    "    return None\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def normalize_party(value: Optional[str]) -> Optional[str]:\n",
    "    \"\"\"\n",
    "    Normalizes a political party acronym.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    value : str, optional\n",
    "        Party acronym.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    str or None\n",
    "        Normalized party acronym.\n",
    "    \"\"\"\n",
    "\n",
    "    normalized_value = normalize_text(value)\n",
    "\n",
    "    if normalized_value is None:\n",
    "        return None\n",
    "\n",
    "    if normalized_value in PARTY_NORMALIZATION_MAP:\n",
    "        return PARTY_NORMALIZATION_MAP[normalized_value]\n",
    "\n",
    "    return normalized_value\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def is_valid_state(value: Optional[str]) -> bool:\n",
    "    \"\"\"\n",
    "    Checks whether a value is a valid Brazilian state acronym.\n",
    "    \"\"\"\n",
    "\n",
    "    return normalize_state(value) is not None\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def is_valid_party(value: Optional[str]) -> bool:\n",
    "    \"\"\"\n",
    "    Checks whether a value is a known party acronym.\n",
    "    \"\"\"\n",
    "\n",
    "    normalized_value = normalize_party(value)\n",
    "\n",
    "    if normalized_value is None:\n",
    "        return False\n",
    "\n",
    "    return normalized_value in VALID_PARTY_ACRONYMS\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def is_valid_legislature(legislature_id: Optional[int]) -> bool:\n",
    "    \"\"\"\n",
    "    Checks whether a legislature identifier is supported by the project scope.\n",
    "    \"\"\"\n",
    "\n",
    "    if legislature_id is None:\n",
    "        return False\n",
    "\n",
    "    try:\n",
    "        return int(legislature_id) in LEGISLATURE_PERIODS\n",
    "\n",
    "    except Exception:\n",
    "        return False\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def get_legislature_period(legislature_id: int) -> Optional[Dict[str, int]]:\n",
    "    \"\"\"\n",
    "    Returns the configured period for a legislature identifier.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    legislature_id : int\n",
    "        Legislature identifier.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    dict or None\n",
    "        Legislature period metadata.\n",
    "    \"\"\"\n",
    "\n",
    "    try:\n",
    "        return LEGISLATURE_PERIODS.get(int(legislature_id))\n",
    "\n",
    "    except Exception:\n",
    "        return None\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def get_legislature_from_year(year: int) -> Optional[int]:\n",
    "    \"\"\"\n",
    "    Returns the legislature identifier associated with a year.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    year : int\n",
    "        Calendar year.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    int or None\n",
    "        Legislature identifier when found.\n",
    "    \"\"\"\n",
    "\n",
    "    if year is None:\n",
    "        return None\n",
    "\n",
    "    try:\n",
    "        year = int(year)\n",
    "\n",
    "    except Exception:\n",
    "        return None\n",
    "\n",
    "    for legislature_id, period in LEGISLATURE_PERIODS.items():\n",
    "        if period[\"start_year\"] <= year <= period[\"end_year\"]:\n",
    "            return legislature_id\n",
    "\n",
    "    return None\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def get_year_from_date(value) -> Optional[int]:\n",
    "    \"\"\"\n",
    "    Extracts the year from a date-like value.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    value : object\n",
    "        Date, timestamp or string value.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    int or None\n",
    "        Extracted year when available.\n",
    "    \"\"\"\n",
    "\n",
    "    if value is None:\n",
    "        return None\n",
    "\n",
    "    try:\n",
    "        return int(str(value)[:4])\n",
    "\n",
    "    except Exception:\n",
    "        return None\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def get_supported_legislatures() -> List[int]:\n",
    "    \"\"\"\n",
    "    Returns the list of legislature identifiers supported by the project.\n",
    "    \"\"\"\n",
    "\n",
    "    return list(LEGISLATURE_PERIODS.keys())\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def get_valid_states() -> List[str]:\n",
    "    \"\"\"\n",
    "    Returns the list of valid Brazilian state acronyms.\n",
    "    \"\"\"\n",
    "\n",
    "    return VALID_STATE_ACRONYMS\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def get_valid_parties() -> List[str]:\n",
    "    \"\"\"\n",
    "    Returns the list of known political party acronyms.\n",
    "    \"\"\"\n",
    "\n",
    "    return VALID_PARTY_ACRONYMS\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "print(\"utils_legislature loaded successfully.\")"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "utils_legislature",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}