{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "41fa291a-d5b2-4fde-a0c9-085ca5ad5c95",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "utils_logger loaded successfully.\n"
     ]
    }
   ],
   "source": [
    "# Databricks notebook source\n",
    "# MAGIC %md\n",
    "# MAGIC # 99 Utils — Console Logger\n",
    "# MAGIC\n",
    "# MAGIC **Notebook:** `utils_logger`\n",
    "# MAGIC\n",
    "# MAGIC Provides standardized console logging utilities for the Brazil Legislative Analytics Medallion pipeline.\n",
    "# MAGIC\n",
    "# MAGIC This notebook centralizes log formatting across Bronze, Silver, Gold, Marts, Quality and Jobs notebooks.\n",
    "# MAGIC\n",
    "# MAGIC ## Responsibilities\n",
    "# MAGIC - Standardize operational logging across pipeline notebooks\n",
    "# MAGIC - Support structured log levels such as INFO, WARNING, SUCCESS and ERROR\n",
    "# MAGIC - Include Medallion layer context in log messages\n",
    "# MAGIC - Improve execution traceability during Databricks notebook runs\n",
    "# MAGIC - Support troubleshooting during API ingestion and transformation steps\n",
    "# MAGIC\n",
    "# MAGIC ## Technical Notes\n",
    "# MAGIC - Python functions and variables are written in English.\n",
    "# MAGIC - Table and field names follow Portuguese mnemonic standards.\n",
    "# MAGIC - Comments and documentation are written in English.\n",
    "# MAGIC - This logger writes messages to the notebook execution output.\n",
    "# MAGIC - Persistent logging is handled by `utils_table_logger`.\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "import logging\n",
    "from typing import Optional\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def get_logger(\n",
    "    logger_name: str,\n",
    "    layer_name: str = \"pipeline\",\n",
    ") -> logging.Logger:\n",
    "    \"\"\"\n",
    "    Creates or retrieves a standardized pipeline logger.\n",
    "    \"\"\"\n",
    "\n",
    "    normalized_layer = layer_name.strip().lower()\n",
    "    full_logger_name = f\"{normalized_layer}.{logger_name}\"\n",
    "\n",
    "    pipeline_logger = logging.getLogger(full_logger_name)\n",
    "\n",
    "    if pipeline_logger.handlers:\n",
    "        return pipeline_logger\n",
    "\n",
    "    pipeline_logger.setLevel(logging.INFO)\n",
    "    pipeline_logger.propagate = False\n",
    "\n",
    "    log_formatter = logging.Formatter(\n",
    "        fmt=\"%(asctime)s | %(levelname)s | %(layer)s | %(name)s | %(message)s\",\n",
    "        datefmt=\"%Y-%m-%d %H:%M:%S\",\n",
    "    )\n",
    "\n",
    "    console_handler = logging.StreamHandler()\n",
    "    console_handler.setLevel(logging.INFO)\n",
    "    console_handler.setFormatter(log_formatter)\n",
    "\n",
    "    class LayerFilter(logging.Filter):\n",
    "        \"\"\"\n",
    "        Adds the Medallion layer name to each log record.\n",
    "        \"\"\"\n",
    "\n",
    "        def filter(self, log_record: logging.LogRecord) -> bool:\n",
    "            log_record.layer = normalized_layer.upper()\n",
    "            return True\n",
    "\n",
    "    console_handler.addFilter(LayerFilter())\n",
    "    pipeline_logger.addHandler(console_handler)\n",
    "\n",
    "    return pipeline_logger\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def log_info(\n",
    "    pipeline_logger: logging.Logger,\n",
    "    message: str,\n",
    ") -> None:\n",
    "    \"\"\"\n",
    "    Registers an informational console log message.\n",
    "    \"\"\"\n",
    "\n",
    "    pipeline_logger.info(message)\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def log_warning(\n",
    "    pipeline_logger: logging.Logger,\n",
    "    message: str,\n",
    ") -> None:\n",
    "    \"\"\"\n",
    "    Registers a warning console log message.\n",
    "    \"\"\"\n",
    "\n",
    "    pipeline_logger.warning(message)\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def log_error(\n",
    "    pipeline_logger: logging.Logger,\n",
    "    message: str,\n",
    "    error: Optional[Exception] = None,\n",
    ") -> None:\n",
    "    \"\"\"\n",
    "    Registers an error console log message.\n",
    "    \"\"\"\n",
    "\n",
    "    if error is not None:\n",
    "        pipeline_logger.error(f\"{message} | error_detail={str(error)}\")\n",
    "    else:\n",
    "        pipeline_logger.error(message)\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "def log_success(\n",
    "    pipeline_logger: logging.Logger,\n",
    "    message: str,\n",
    ") -> None:\n",
    "    \"\"\"\n",
    "    Registers a success console log message.\n",
    "\n",
    "    Notes\n",
    "    -----\n",
    "    Python logging does not provide a native SUCCESS level.\n",
    "    For Databricks compatibility, SUCCESS is registered as INFO with a prefix.\n",
    "    \"\"\"\n",
    "\n",
    "    pipeline_logger.info(f\"[SUCCESS] {message}\")\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "print(\"utils_logger loaded successfully.\")"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "utils_logger",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}