{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "collapsed": true,
     "inputWidgets": {},
     "nuid": "ddaf837e-4905-40a3-961f-edf2e3eb9ec6",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "%run ../99_utils/utils_config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "collapsed": true,
     "inputWidgets": {},
     "nuid": "03eec430-7856-4cec-b6e7-934183b13659",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PROJECT CONFIGURATION LOADED SUCCESSFULLY\nPROJECT_NAME: brazil_legislative_analytics\nPROJECT_VERSION: v1.0.0\nPROJECT_ENVIRONMENT: dev\nCATALOG_NAME: brazil_legislative_analytics\nRUN_ID: c1a8a41c-306d-41c7-9851-786d60a7e41b\n"
     ]
    }
   ],
   "source": [
    "%run ../99_utils/utils_logger"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "collapsed": true,
     "inputWidgets": {},
     "nuid": "dc88f514-5902-4404-a708-f623f9cea389",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "utils_config loaded successfully.\n"
     ]
    },
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "utils_logger loaded successfully.\n"
     ]
    }
   ],
   "source": [
    "%run ../99_utils/utils_table_logger"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "bdecb051-10b7-4b33-8cf0-beaa1435555a",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "==========================================================================================\nBRAZIL LEGISLATIVE ANALYTICS MEDALLION\n01 - RUN FULL PIPELINE\n==========================================================================================\nExecution Timestamp: 2026-05-20 04:38:40.630501\nCatalog: brazil_legislative_analytics\nEnvironment: dev\n==========================================================================================\n"
     ]
    },
    {
     "output_type": "stream",
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-05-20 04:38:42 | INFO | JOBS | jobs.01_run_full_pipeline | Starting step: validate_project_setup\n2026-05-20 04:39:15 | INFO | JOBS | jobs.01_run_full_pipeline | [SUCCESS] Step completed: validate_project_setup\n2026-05-20 04:39:16 | INFO | JOBS | jobs.01_run_full_pipeline | Starting step: validate_api_connection\n2026-05-20 04:39:39 | INFO | JOBS | jobs.01_run_full_pipeline | [SUCCESS] Step completed: validate_api_connection\n2026-05-20 04:39:40 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: bronze_deputados\n2026-05-20 04:39:42 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: bronze_frentes\n2026-05-20 04:39:44 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: bronze_frentes_membros\n2026-05-20 04:39:46 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: bronze_frentes_detalhes\n2026-05-20 04:39:47 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: bronze_eventos\n2026-05-20 04:39:49 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: bronze_votacoes\n2026-05-20 04:39:51 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: bronze_votos\n2026-05-20 04:39:52 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: bronze_despesas_ceap\n2026-05-20 04:39:54 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: bronze_cpis\n2026-05-20 04:39:56 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: bronze_cpi_eventos\n2026-05-20 04:39:58 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: bronze_proposicoes\n2026-05-20 04:40:00 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: silver_deputados\n2026-05-20 04:40:04 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: silver_partidos\n2026-05-20 04:40:07 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: silver_estados\n2026-05-20 04:40:08 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: silver_frentes\n2026-05-20 04:40:09 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: silver_frentes_membros\n2026-05-20 04:40:11 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: silver_eventos\n2026-05-20 04:40:12 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: silver_votacoes\n2026-05-20 04:40:14 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: silver_votos\n2026-05-20 04:40:15 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: silver_despesas_ceap\n2026-05-20 04:40:17 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: silver_fornecedores\n2026-05-20 04:40:18 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: silver_cpis\n2026-05-20 04:40:20 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: silver_cpi_eventos\n2026-05-20 04:40:22 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: silver_proposicoes\n2026-05-20 04:40:23 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_dm_deputado\n2026-05-20 04:40:24 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_dm_partido\n2026-05-20 04:40:25 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_dm_estado\n2026-05-20 04:40:27 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_dm_data\n2026-05-20 04:40:29 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_dm_orgao\n2026-05-20 04:40:30 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_dm_tipo_evento\n2026-05-20 04:40:32 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_dm_evento\n2026-05-20 04:40:33 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_dm_votacao\n2026-05-20 04:40:35 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_dm_tipo_votacao\n2026-05-20 04:40:36 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_dm_frente\n2026-05-20 04:40:37 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_dm_fornecedor\n2026-05-20 04:40:38 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_dm_cpi\n2026-05-20 04:40:40 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_ft_frentes_membros\n2026-05-20 04:40:41 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_ft_eventos_presencas\n2026-05-20 04:40:43 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_ft_resultados_votacoes\n2026-05-20 04:40:44 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_ft_despesas_ceap\n2026-05-20 04:40:46 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: gold_ft_cpi_eventos\n2026-05-20 04:40:47 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: mart_atlas_frentes\n2026-05-20 04:40:49 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: mart_calendario_eventos\n2026-05-20 04:40:51 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: mart_correlacao_frentes_votacoes\n2026-05-20 04:40:53 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: mart_panorama_despesas_ceap\n2026-05-20 04:40:54 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: mart_auditoria_cpis\n2026-05-20 04:40:56 | WARNING | JOBS | jobs.01_run_full_pipeline | Step skipped: mart_monitor_presenca_absenteismo\n2026-05-20 04:40:57 | INFO | JOBS | jobs.01_run_full_pipeline | Starting step: quality_bronze_checks\n2026-05-20 04:41:19 | INFO | JOBS | jobs.01_run_full_pipeline | [SUCCESS] Step completed: quality_bronze_checks\n2026-05-20 04:41:21 | INFO | JOBS | jobs.01_run_full_pipeline | Starting step: quality_silver_checks\n2026-05-20 04:41:43 | INFO | JOBS | jobs.01_run_full_pipeline | [SUCCESS] Step completed: quality_silver_checks\n2026-05-20 04:41:45 | INFO | JOBS | jobs.01_run_full_pipeline | Starting step: quality_gold_checks\n2026-05-20 04:42:07 | INFO | JOBS | jobs.01_run_full_pipeline | [SUCCESS] Step completed: quality_gold_checks\n2026-05-20 04:42:08 | INFO | JOBS | jobs.01_run_full_pipeline | Starting step: quality_traceability_checks\n2026-05-20 04:42:31 | INFO | JOBS | jobs.01_run_full_pipeline | [SUCCESS] Step completed: quality_traceability_checks\n"
     ]
    },
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "==========================================================================================\nFULL PIPELINE SUMMARY\n==========================================================================================\nJob Run ID: b6d8a5d3-16d2-4f5e-b413-c6ac3ff8fb8c\nTotal steps: 53\nSuccessful steps: 6\nWarning steps: 47\nFailed steps: 0\nPipeline duration seconds: 230.696849\n==========================================================================================\nFULL PIPELINE EXECUTION COMPLETED\n"
     ]
    },
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PROJECT CONFIGURATION LOADED SUCCESSFULLY\nPROJECT_NAME: brazil_legislative_analytics\nPROJECT_VERSION: v1.0.0\nPROJECT_ENVIRONMENT: dev\nCATALOG_NAME: brazil_legislative_analytics\nRUN_ID: df48d370-e1b5-4bef-9014-0befa8f7c733\n"
     ]
    },
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "utils_config loaded successfully.\n"
     ]
    },
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "utils_table_logger loaded successfully.\n"
     ]
    }
   ],
   "source": [
    "# Databricks notebook source\n",
    "# MAGIC %md\n",
    "# MAGIC # 01 Job — Run Full Pipeline\n",
    "# MAGIC\n",
    "# MAGIC Orchestrates the complete execution flow of the Brazil Legislative Analytics Medallion project.\n",
    "# MAGIC\n",
    "# MAGIC ## Purpose\n",
    "# MAGIC This notebook executes the project pipeline in the expected order, from setup validation to quality checks.\n",
    "# MAGIC\n",
    "# MAGIC ## Execution Flow\n",
    "# MAGIC - Validate project setup\n",
    "# MAGIC - Optionally validate API connection\n",
    "# MAGIC - Execute Bronze ingestion notebooks\n",
    "# MAGIC - Execute Silver transformation notebooks\n",
    "# MAGIC - Execute Gold dimensional modeling notebooks\n",
    "# MAGIC - Execute Marts notebooks\n",
    "# MAGIC - Execute Quality notebooks\n",
    "# MAGIC\n",
    "# MAGIC ## Current Development Note\n",
    "# MAGIC Some Bronze, Silver, Gold and Marts notebooks may still be under development.\n",
    "# MAGIC In this case, the corresponding execution blocks can remain disabled until the notebooks are available.\n",
    "# MAGIC\n",
    "# MAGIC ## API Validation Note\n",
    "# MAGIC The API validation notebook is intentionally disabled by default in the full pipeline because external API endpoints may be unstable or slow in Databricks Free Edition.\n",
    "# MAGIC It should be executed manually or as a separated job when deep API validation is required.\n",
    "# MAGIC\n",
    "# MAGIC ## Documentation Standard\n",
    "# MAGIC - Python functions and variables are written in English.\n",
    "# MAGIC - Table and field names follow Portuguese mnemonic standards.\n",
    "# MAGIC - Comments and documentation are written in English.\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %run ../99_utils/utils_config\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %run ../99_utils/utils_logger\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %run ../99_utils/utils_table_logger\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "from datetime import datetime\n",
    "import time\n",
    "import uuid\n",
    "import traceback\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "print(\"=\" * 90)\n",
    "print(\"BRAZIL LEGISLATIVE ANALYTICS MEDALLION\")\n",
    "print(\"01 - RUN FULL PIPELINE\")\n",
    "print(\"=\" * 90)\n",
    "print(f\"Execution Timestamp: {datetime.now()}\")\n",
    "print(f\"Catalog: {CATALOG_NAME}\")\n",
    "print(f\"Environment: {PROJECT_ENVIRONMENT}\")\n",
    "print(\"=\" * 90)\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# ============================================================\n",
    "# JOB CONFIGURATION\n",
    "# ============================================================\n",
    "\n",
    "NOTEBOOK_NAME = \"01_run_full_pipeline\"\n",
    "LAYER_NAME = \"jobs\"\n",
    "ENTITY_NAME = \"full_pipeline\"\n",
    "\n",
    "JOB_RUN_ID = str(uuid.uuid4())\n",
    "\n",
    "# During development, keep this as False to avoid stopping\n",
    "# the full job when optional or not-yet-built notebooks are missing.\n",
    "FAIL_ON_STEP_ERROR = False\n",
    "\n",
    "PIPELINE_LOG_TABLE = (\n",
    "    f\"{CATALOG_NAME}.\"\n",
    "    f\"{SCHEMA_AUDIT}.\"\n",
    "    f\"{AUD_TB_LOG_EXECUCAO_PIPELINE}\"\n",
    ")\n",
    "\n",
    "PIPELINE_ERROR_TABLE = (\n",
    "    f\"{CATALOG_NAME}.\"\n",
    "    f\"{SCHEMA_AUDIT}.\"\n",
    "    f\"{AUD_TB_LOG_ERROS_PIPELINE}\"\n",
    ")\n",
    "\n",
    "logger = get_logger(\n",
    "    logger_name=NOTEBOOK_NAME,\n",
    "    layer_name=LAYER_NAME,\n",
    ")\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# ============================================================\n",
    "# PIPELINE STEP CONFIGURATION\n",
    "# ============================================================\n",
    "#\n",
    "# Set enabled=True only when the referenced notebook exists and\n",
    "# is ready to execute.\n",
    "#\n",
    "# API validation is disabled by default in the full pipeline\n",
    "# because the external API may be slow or unstable.\n",
    "#\n",
    "# ============================================================\n",
    "\n",
    "PIPELINE_STEPS = [\n",
    "    {\n",
    "        \"step_name\": \"validate_project_setup\",\n",
    "        \"notebook_path\": \"../00_setup/90_validate_project_setup\",\n",
    "        \"layer_name\": \"setup\",\n",
    "        \"entity_name\": \"project_setup\",\n",
    "        \"enabled\": True,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"validate_api_connection\",\n",
    "        \"notebook_path\": \"../00_setup/92_validate_api_connection\",\n",
    "        \"layer_name\": \"setup\",\n",
    "        \"entity_name\": \"api_connection\",\n",
    "        \"enabled\": True,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "\n",
    "    # Bronze ingestion notebooks.\n",
    "    {\n",
    "        \"step_name\": \"bronze_deputados\",\n",
    "        \"notebook_path\": \"../01_bronze/01_bronze_deputados\",\n",
    "        \"layer_name\": \"bronze\",\n",
    "        \"entity_name\": \"deputados\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"bronze_frentes\",\n",
    "        \"notebook_path\": \"../01_bronze/02_bronze_frentes\",\n",
    "        \"layer_name\": \"bronze\",\n",
    "        \"entity_name\": \"frentes\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"bronze_frentes_membros\",\n",
    "        \"notebook_path\": \"../01_bronze/03_bronze_frentes_membros\",\n",
    "        \"layer_name\": \"bronze\",\n",
    "        \"entity_name\": \"frentes_membros\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"bronze_frentes_detalhes\",\n",
    "        \"notebook_path\": \"../01_bronze/03a_bronze_frentes_detalhes\",\n",
    "        \"layer_name\": \"bronze\",\n",
    "        \"entity_name\": \"frentes_detalhes\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": False,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"bronze_eventos\",\n",
    "        \"notebook_path\": \"../01_bronze/04_bronze_eventos\",\n",
    "        \"layer_name\": \"bronze\",\n",
    "        \"entity_name\": \"eventos\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"bronze_votacoes\",\n",
    "        \"notebook_path\": \"../01_bronze/05_bronze_votacoes\",\n",
    "        \"layer_name\": \"bronze\",\n",
    "        \"entity_name\": \"votacoes\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"bronze_votos\",\n",
    "        \"notebook_path\": \"../01_bronze/06_bronze_votos\",\n",
    "        \"layer_name\": \"bronze\",\n",
    "        \"entity_name\": \"votos\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"bronze_despesas_ceap\",\n",
    "        \"notebook_path\": \"../01_bronze/07_bronze_despesas_ceap\",\n",
    "        \"layer_name\": \"bronze\",\n",
    "        \"entity_name\": \"despesas_ceap\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"bronze_cpis\",\n",
    "        \"notebook_path\": \"../01_bronze/08_bronze_cpis\",\n",
    "        \"layer_name\": \"bronze\",\n",
    "        \"entity_name\": \"cpis\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"bronze_cpi_eventos\",\n",
    "        \"notebook_path\": \"../01_bronze/09_bronze_cpi_eventos\",\n",
    "        \"layer_name\": \"bronze\",\n",
    "        \"entity_name\": \"cpi_eventos\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": False,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"bronze_proposicoes\",\n",
    "        \"notebook_path\": \"../01_bronze/10_bronze_proposicoes\",\n",
    "        \"layer_name\": \"bronze\",\n",
    "        \"entity_name\": \"proposicoes\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "\n",
    "    # Silver transformation notebooks.\n",
    "    {\n",
    "        \"step_name\": \"silver_deputados\",\n",
    "        \"notebook_path\": \"../02_silver/01_silver_deputados\",\n",
    "        \"layer_name\": \"silver\",\n",
    "        \"entity_name\": \"deputados\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"silver_partidos\",\n",
    "        \"notebook_path\": \"../02_silver/02_silver_partidos\",\n",
    "        \"layer_name\": \"silver\",\n",
    "        \"entity_name\": \"partidos\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"silver_estados\",\n",
    "        \"notebook_path\": \"../02_silver/03_silver_estados\",\n",
    "        \"layer_name\": \"silver\",\n",
    "        \"entity_name\": \"estados\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"silver_frentes\",\n",
    "        \"notebook_path\": \"../02_silver/04_silver_frentes\",\n",
    "        \"layer_name\": \"silver\",\n",
    "        \"entity_name\": \"frentes\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"silver_frentes_membros\",\n",
    "        \"notebook_path\": \"../02_silver/05_silver_frentes_membros\",\n",
    "        \"layer_name\": \"silver\",\n",
    "        \"entity_name\": \"frentes_membros\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"silver_eventos\",\n",
    "        \"notebook_path\": \"../02_silver/06_silver_eventos\",\n",
    "        \"layer_name\": \"silver\",\n",
    "        \"entity_name\": \"eventos\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"silver_votacoes\",\n",
    "        \"notebook_path\": \"../02_silver/07_silver_votacoes\",\n",
    "        \"layer_name\": \"silver\",\n",
    "        \"entity_name\": \"votacoes\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"silver_votos\",\n",
    "        \"notebook_path\": \"../02_silver/08_silver_votos\",\n",
    "        \"layer_name\": \"silver\",\n",
    "        \"entity_name\": \"votos\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"silver_despesas_ceap\",\n",
    "        \"notebook_path\": \"../02_silver/09_silver_despesas_ceap\",\n",
    "        \"layer_name\": \"silver\",\n",
    "        \"entity_name\": \"despesas_ceap\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"silver_fornecedores\",\n",
    "        \"notebook_path\": \"../02_silver/10_silver_fornecedores\",\n",
    "        \"layer_name\": \"silver\",\n",
    "        \"entity_name\": \"fornecedores\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"silver_cpis\",\n",
    "        \"notebook_path\": \"../02_silver/11_silver_cpis\",\n",
    "        \"layer_name\": \"silver\",\n",
    "        \"entity_name\": \"cpis\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"silver_cpi_eventos\",\n",
    "        \"notebook_path\": \"../02_silver/12_silver_cpi_eventos\",\n",
    "        \"layer_name\": \"silver\",\n",
    "        \"entity_name\": \"cpi_eventos\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"silver_proposicoes\",\n",
    "        \"notebook_path\": \"../02_silver/13_silver_proposicoes\",\n",
    "        \"layer_name\": \"silver\",\n",
    "        \"entity_name\": \"proposicoes\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "\n",
    "    # Gold dimensional modeling notebooks.\n",
    "    {\n",
    "        \"step_name\": \"gold_dm_deputado\",\n",
    "        \"notebook_path\": \"../03_gold/01_dm_deputado\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"dm_deputado\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_dm_partido\",\n",
    "        \"notebook_path\": \"../03_gold/02_dm_partido\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"dm_partido\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_dm_estado\",\n",
    "        \"notebook_path\": \"../03_gold/03_dm_estado\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"dm_estado\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_dm_data\",\n",
    "        \"notebook_path\": \"../03_gold/04_dm_data\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"dm_data\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_dm_orgao\",\n",
    "        \"notebook_path\": \"../03_gold/05_dm_orgao\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"dm_orgao\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_dm_tipo_evento\",\n",
    "        \"notebook_path\": \"../03_gold/06_dm_tipo_evento\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"dm_tipo_evento\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_dm_evento\",\n",
    "        \"notebook_path\": \"../03_gold/07_dm_evento\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"dm_evento\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_dm_votacao\",\n",
    "        \"notebook_path\": \"../03_gold/08_dm_votacao\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"dm_votacao\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_dm_tipo_votacao\",\n",
    "        \"notebook_path\": \"../03_gold/09_dm_tipo_votacao\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"dm_tipo_votacao\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_dm_frente\",\n",
    "        \"notebook_path\": \"../03_gold/10_dm_frente\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"dm_frente\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_dm_fornecedor\",\n",
    "        \"notebook_path\": \"../03_gold/11_dm_fornecedor\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"dm_fornecedor\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_dm_cpi\",\n",
    "        \"notebook_path\": \"../03_gold/12_dm_cpi\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"dm_cpi\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_ft_frentes_membros\",\n",
    "        \"notebook_path\": \"../03_gold/13_ft_frentes_membros\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"ft_frentes_membros\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_ft_eventos_presencas\",\n",
    "        \"notebook_path\": \"../03_gold/14_ft_eventos_presencas\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"ft_eventos_presencas\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_ft_resultados_votacoes\",\n",
    "        \"notebook_path\": \"../03_gold/15_ft_resultados_votacoes\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"ft_resultados_votacoes\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_ft_despesas_ceap\",\n",
    "        \"notebook_path\": \"../03_gold/16_ft_despesas_ceap\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"ft_despesas_ceap\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"gold_ft_cpi_eventos\",\n",
    "        \"notebook_path\": \"../03_gold/17_ft_cpi_eventos\",\n",
    "        \"layer_name\": \"gold\",\n",
    "        \"entity_name\": \"ft_cpi_eventos\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "\n",
    "    # Marts.\n",
    "    {\n",
    "        \"step_name\": \"mart_atlas_frentes\",\n",
    "        \"notebook_path\": \"../04_marts/01_am_atlas_frentes\",\n",
    "        \"layer_name\": \"marts\",\n",
    "        \"entity_name\": \"atlas_frentes\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"mart_calendario_eventos\",\n",
    "        \"notebook_path\": \"../04_marts/02_am_calendario_eventos\",\n",
    "        \"layer_name\": \"marts\",\n",
    "        \"entity_name\": \"calendario_eventos\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"mart_correlacao_frentes_votacoes\",\n",
    "        \"notebook_path\": \"../04_marts/03_am_correlacao_frentes_votacoes\",\n",
    "        \"layer_name\": \"marts\",\n",
    "        \"entity_name\": \"correlacao_frentes_votacoes\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"mart_panorama_despesas_ceap\",\n",
    "        \"notebook_path\": \"../04_marts/04_am_panorama_despesas_ceap\",\n",
    "        \"layer_name\": \"marts\",\n",
    "        \"entity_name\": \"panorama_despesas_ceap\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"mart_auditoria_cpis\",\n",
    "        \"notebook_path\": \"../04_marts/05_am_auditoria_cpis\",\n",
    "        \"layer_name\": \"marts\",\n",
    "        \"entity_name\": \"auditoria_cpis\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"mart_monitor_presenca_absenteismo\",\n",
    "        \"notebook_path\": \"../04_marts/06_am_monitor_presenca_absenteismo\",\n",
    "        \"layer_name\": \"marts\",\n",
    "        \"entity_name\": \"monitor_presenca_absenteismo\",\n",
    "        \"enabled\": False,\n",
    "        \"critical\": True,\n",
    "    },\n",
    "\n",
    "    # Quality notebooks.\n",
    "    {\n",
    "        \"step_name\": \"quality_bronze_checks\",\n",
    "        \"notebook_path\": \"../06_quality/01_quality_bronze_checks\",\n",
    "        \"layer_name\": \"quality\",\n",
    "        \"entity_name\": \"bronze_checks\",\n",
    "        \"enabled\": True,\n",
    "        \"critical\": False,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"quality_silver_checks\",\n",
    "        \"notebook_path\": \"../06_quality/02_quality_silver_checks\",\n",
    "        \"layer_name\": \"quality\",\n",
    "        \"entity_name\": \"silver_checks\",\n",
    "        \"enabled\": True,\n",
    "        \"critical\": False,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"quality_gold_checks\",\n",
    "        \"notebook_path\": \"../06_quality/03_quality_gold_checks\",\n",
    "        \"layer_name\": \"quality\",\n",
    "        \"entity_name\": \"gold_checks\",\n",
    "        \"enabled\": True,\n",
    "        \"critical\": False,\n",
    "    },\n",
    "    {\n",
    "        \"step_name\": \"quality_traceability_checks\",\n",
    "        \"notebook_path\": \"../06_quality/04_traceability_checks\",\n",
    "        \"layer_name\": \"quality\",\n",
    "        \"entity_name\": \"traceability_checks\",\n",
    "        \"enabled\": True,\n",
    "        \"critical\": False,\n",
    "    },\n",
    "]\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# ============================================================\n",
    "# JOB HELPERS\n",
    "# ============================================================\n",
    "\n",
    "def run_notebook_step(\n",
    "    step_config: dict,\n",
    ") -> dict:\n",
    "    \"\"\"\n",
    "    Executes a configured notebook step and returns execution metadata.\n",
    "    \"\"\"\n",
    "\n",
    "    step_name = step_config[\"step_name\"]\n",
    "    notebook_path = step_config[\"notebook_path\"]\n",
    "    step_layer = step_config[\"layer_name\"]\n",
    "    step_entity = step_config[\"entity_name\"]\n",
    "    is_enabled = step_config[\"enabled\"]\n",
    "    is_critical = step_config[\"critical\"]\n",
    "\n",
    "    step_log_id = str(uuid.uuid4())\n",
    "    started_at = datetime.now()\n",
    "    status = EXECUTION_STATUS_STARTED\n",
    "    message = \"Step execution started.\"\n",
    "\n",
    "    if not is_enabled:\n",
    "\n",
    "        finished_at = datetime.now()\n",
    "        duration_seconds = (\n",
    "            finished_at - started_at\n",
    "        ).total_seconds()\n",
    "\n",
    "        write_pipeline_log(\n",
    "            log_id=step_log_id,\n",
    "            execution_id=JOB_RUN_ID,\n",
    "            notebook_name=NOTEBOOK_NAME,\n",
    "            layer_name=step_layer,\n",
    "            entity_name=step_entity,\n",
    "            target_table=\"not_applicable\",\n",
    "            status=EXECUTION_STATUS_WARNING,\n",
    "            message=f\"Step skipped because it is disabled: {step_name}\",\n",
    "            started_at=started_at,\n",
    "            finished_at=finished_at,\n",
    "            duration_seconds=duration_seconds,\n",
    "            records_read=None,\n",
    "            records_written=None,\n",
    "        )\n",
    "\n",
    "        log_warning(\n",
    "            pipeline_logger=logger,\n",
    "            message=f\"Step skipped: {step_name}\",\n",
    "        )\n",
    "\n",
    "        return {\n",
    "            \"step_name\": step_name,\n",
    "            \"status\": EXECUTION_STATUS_WARNING,\n",
    "            \"message\": \"Step skipped because it is disabled.\",\n",
    "            \"duration_seconds\": duration_seconds,\n",
    "            \"critical\": is_critical,\n",
    "        }\n",
    "\n",
    "    try:\n",
    "\n",
    "        write_pipeline_log(\n",
    "            log_id=step_log_id,\n",
    "            execution_id=JOB_RUN_ID,\n",
    "            notebook_name=NOTEBOOK_NAME,\n",
    "            layer_name=step_layer,\n",
    "            entity_name=step_entity,\n",
    "            target_table=\"not_applicable\",\n",
    "            status=status,\n",
    "            message=message,\n",
    "            started_at=started_at,\n",
    "            finished_at=None,\n",
    "            duration_seconds=None,\n",
    "            records_read=None,\n",
    "            records_written=None,\n",
    "        )\n",
    "\n",
    "        log_info(\n",
    "            pipeline_logger=logger,\n",
    "            message=f\"Starting step: {step_name}\",\n",
    "        )\n",
    "\n",
    "        dbutils.notebook.run(\n",
    "            notebook_path,\n",
    "            timeout_seconds=0,\n",
    "        )\n",
    "\n",
    "        finished_at = datetime.now()\n",
    "        duration_seconds = (\n",
    "            finished_at - started_at\n",
    "        ).total_seconds()\n",
    "\n",
    "        write_pipeline_log(\n",
    "            log_id=str(uuid.uuid4()),\n",
    "            execution_id=JOB_RUN_ID,\n",
    "            notebook_name=NOTEBOOK_NAME,\n",
    "            layer_name=step_layer,\n",
    "            entity_name=step_entity,\n",
    "            target_table=\"not_applicable\",\n",
    "            status=EXECUTION_STATUS_SUCCESS,\n",
    "            message=f\"Step completed successfully: {step_name}\",\n",
    "            started_at=started_at,\n",
    "            finished_at=finished_at,\n",
    "            duration_seconds=duration_seconds,\n",
    "            records_read=None,\n",
    "            records_written=None,\n",
    "        )\n",
    "\n",
    "        log_success(\n",
    "            pipeline_logger=logger,\n",
    "            message=f\"Step completed: {step_name}\",\n",
    "        )\n",
    "\n",
    "        return {\n",
    "            \"step_name\": step_name,\n",
    "            \"status\": EXECUTION_STATUS_SUCCESS,\n",
    "            \"message\": \"Step completed successfully.\",\n",
    "            \"duration_seconds\": duration_seconds,\n",
    "            \"critical\": is_critical,\n",
    "        }\n",
    "\n",
    "    except Exception as error:\n",
    "\n",
    "        finished_at = datetime.now()\n",
    "        duration_seconds = (\n",
    "            finished_at - started_at\n",
    "        ).total_seconds()\n",
    "\n",
    "        error_message = str(error)\n",
    "        error_stacktrace = traceback.format_exc()\n",
    "\n",
    "        write_pipeline_log(\n",
    "            log_id=str(uuid.uuid4()),\n",
    "            execution_id=JOB_RUN_ID,\n",
    "            notebook_name=NOTEBOOK_NAME,\n",
    "            layer_name=step_layer,\n",
    "            entity_name=step_entity,\n",
    "            target_table=\"not_applicable\",\n",
    "            status=EXECUTION_STATUS_FAILED,\n",
    "            message=f\"Step failed: {step_name} | {error_message}\",\n",
    "            started_at=started_at,\n",
    "            finished_at=finished_at,\n",
    "            duration_seconds=duration_seconds,\n",
    "            records_read=None,\n",
    "            records_written=None,\n",
    "        )\n",
    "\n",
    "        log_error(\n",
    "            pipeline_logger=logger,\n",
    "            message=f\"Step failed: {step_name}\",\n",
    "            error=error,\n",
    "        )\n",
    "\n",
    "        return {\n",
    "            \"step_name\": step_name,\n",
    "            \"status\": EXECUTION_STATUS_FAILED,\n",
    "            \"message\": error_message,\n",
    "            \"duration_seconds\": duration_seconds,\n",
    "            \"critical\": is_critical,\n",
    "            \"stacktrace\": error_stacktrace,\n",
    "        }\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %md\n",
    "# MAGIC ## 1. Execute Pipeline Steps\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "pipeline_results = []\n",
    "\n",
    "pipeline_started_at = datetime.now()\n",
    "\n",
    "for step_config in PIPELINE_STEPS:\n",
    "\n",
    "    step_result = run_notebook_step(\n",
    "        step_config=step_config,\n",
    "    )\n",
    "\n",
    "    pipeline_results.append(step_result)\n",
    "\n",
    "    if (\n",
    "        step_result[\"status\"] == EXECUTION_STATUS_FAILED\n",
    "        and step_result[\"critical\"]\n",
    "        and FAIL_ON_STEP_ERROR\n",
    "    ):\n",
    "\n",
    "        raise Exception(\n",
    "            f\"Critical pipeline step failed: \"\n",
    "            f\"{step_result['step_name']} | \"\n",
    "            f\"{step_result['message']}\"\n",
    "        )\n",
    "\n",
    "pipeline_finished_at = datetime.now()\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %md\n",
    "# MAGIC ## 2. Pipeline Summary\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "total_steps = len(pipeline_results)\n",
    "\n",
    "success_steps = len([\n",
    "    result\n",
    "    for result in pipeline_results\n",
    "    if result[\"status\"] == EXECUTION_STATUS_SUCCESS\n",
    "])\n",
    "\n",
    "warning_steps = len([\n",
    "    result\n",
    "    for result in pipeline_results\n",
    "    if result[\"status\"] == EXECUTION_STATUS_WARNING\n",
    "])\n",
    "\n",
    "failed_steps = len([\n",
    "    result\n",
    "    for result in pipeline_results\n",
    "    if result[\"status\"] == EXECUTION_STATUS_FAILED\n",
    "])\n",
    "\n",
    "pipeline_duration_seconds = (\n",
    "    pipeline_finished_at - pipeline_started_at\n",
    ").total_seconds()\n",
    "\n",
    "print(\"=\" * 90)\n",
    "print(\"FULL PIPELINE SUMMARY\")\n",
    "print(\"=\" * 90)\n",
    "print(f\"Job Run ID: {JOB_RUN_ID}\")\n",
    "print(f\"Total steps: {total_steps}\")\n",
    "print(f\"Successful steps: {success_steps}\")\n",
    "print(f\"Warning steps: {warning_steps}\")\n",
    "print(f\"Failed steps: {failed_steps}\")\n",
    "print(f\"Pipeline duration seconds: {pipeline_duration_seconds}\")\n",
    "print(\"=\" * 90)\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# ============================================================\n",
    "# FINAL JOB LOG\n",
    "# ============================================================\n",
    "\n",
    "final_status = (\n",
    "    EXECUTION_STATUS_FAILED\n",
    "    if failed_steps > 0\n",
    "    else EXECUTION_STATUS_SUCCESS\n",
    ")\n",
    "\n",
    "write_pipeline_log(\n",
    "    log_id=str(uuid.uuid4()),\n",
    "    execution_id=JOB_RUN_ID,\n",
    "    notebook_name=NOTEBOOK_NAME,\n",
    "    layer_name=LAYER_NAME,\n",
    "    entity_name=ENTITY_NAME,\n",
    "    target_table=PIPELINE_LOG_TABLE,\n",
    "    status=final_status,\n",
    "    message=(\n",
    "        f\"Full pipeline finished. \"\n",
    "        f\"success={success_steps}, \"\n",
    "        f\"warning={warning_steps}, \"\n",
    "        f\"failed={failed_steps}\"\n",
    "    ),\n",
    "    started_at=pipeline_started_at,\n",
    "    finished_at=pipeline_finished_at,\n",
    "    duration_seconds=pipeline_duration_seconds,\n",
    "    records_read=None,\n",
    "    records_written=None,\n",
    ")\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "if failed_steps > 0:\n",
    "\n",
    "    print(\n",
    "        f\"WARNING: Full pipeline finished with \"\n",
    "        f\"{failed_steps} failed step(s).\"\n",
    "    )\n",
    "\n",
    "    if FAIL_ON_STEP_ERROR:\n",
    "        raise Exception(\n",
    "            f\"Full pipeline failed with \"\n",
    "            f\"{failed_steps} failed step(s).\"\n",
    "        )\n",
    "\n",
    "print(\"FULL PIPELINE EXECUTION COMPLETED\")"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "01_run_full_pipeline",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}