{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "49ffd37e-b94a-4e18-bd9e-82fc642a308d",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "================================================================================\nBRAZIL LEGISLATIVE ANALYTICS MEDALLION\n01 - PROJECT CONFIGURATION\n================================================================================\nProject Name: Brazil Legislative Analytics Medallion\nProject Code: BLAM\nEnvironment: dev\nPipeline Version: v1.0\nExecution Timestamp: 2026-05-17 04:30:12.457540\nRun ID: 6e7bf829-88ca-4eaa-b4b8-683eb2f67d9c\n================================================================================\nCatalog: brazil_legislative_analytics\nAudit Schema: brazil_legislative_analytics.audit\nBronze Schema: brazil_legislative_analytics.bronze\nSilver Base Schema: brazil_legislative_analytics.silver_base\nSilver Curated Schema: brazil_legislative_analytics.silver_curated\nGold Schema: brazil_legislative_analytics.gold\nMarts Schema: brazil_legislative_analytics.marts\n================================================================================\nPROJECT CONFIGURATION LOADED SUCCESSFULLY\n================================================================================\n"
     ]
    }
   ],
   "source": [
    "# Databricks notebook source\n",
    "# MAGIC %md\n",
    "# MAGIC # 01_project_config\n",
    "# MAGIC\n",
    "# MAGIC ## Purpose\n",
    "# MAGIC Centralize all project configuration variables used across the Medallion pipeline.\n",
    "# MAGIC\n",
    "# MAGIC ## Layer\n",
    "# MAGIC Setup / Configuration\n",
    "# MAGIC\n",
    "# MAGIC ## Output\n",
    "# MAGIC This notebook does not create tables or persist data. It defines reusable variables\n",
    "# MAGIC for downstream notebooks.\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "from datetime import datetime\n",
    "import uuid\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# Project metadata\n",
    "PROJECT_NAME = \"Brazil Legislative Analytics Medallion\"\n",
    "PROJECT_CODE = \"BLAM\"\n",
    "PIPELINE_VERSION = \"v1.0\"\n",
    "ENVIRONMENT = \"dev\"\n",
    "\n",
    "RUN_ID = str(uuid.uuid4())\n",
    "EXECUTION_TIMESTAMP = datetime.now()\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# Catalog\n",
    "CATALOG_NAME = \"brazil_legislative_analytics\"\n",
    "\n",
    "# Schemas\n",
    "AUDIT_SCHEMA_NAME = \"audit\"\n",
    "BRONZE_SCHEMA_NAME = \"bronze\"\n",
    "SILVER_BASE_SCHEMA_NAME = \"silver_base\"\n",
    "SILVER_CURATED_SCHEMA_NAME = \"silver_curated\"\n",
    "GOLD_SCHEMA_NAME = \"gold\"\n",
    "MARTS_SCHEMA_NAME = \"marts\"\n",
    "\n",
    "# Fully qualified schemas\n",
    "AUDIT_SCHEMA = f\"{CATALOG_NAME}.{AUDIT_SCHEMA_NAME}\"\n",
    "BRONZE_SCHEMA = f\"{CATALOG_NAME}.{BRONZE_SCHEMA_NAME}\"\n",
    "SILVER_BASE_SCHEMA = f\"{CATALOG_NAME}.{SILVER_BASE_SCHEMA_NAME}\"\n",
    "SILVER_CURATED_SCHEMA = f\"{CATALOG_NAME}.{SILVER_CURATED_SCHEMA_NAME}\"\n",
    "GOLD_SCHEMA = f\"{CATALOG_NAME}.{GOLD_SCHEMA_NAME}\"\n",
    "MARTS_SCHEMA = f\"{CATALOG_NAME}.{MARTS_SCHEMA_NAME}\"\n",
    "\n",
    "spark.sql(f\"USE CATALOG {CATALOG_NAME}\")\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# Table naming standards\n",
    "DIMENSION_PREFIX = \"dm\"\n",
    "FACT_PREFIX = \"ft\"\n",
    "MART_PREFIX = \"am\"\n",
    "REFERENCE_PREFIX = \"ref\"\n",
    "VIEW_PREFIX = \"vw\"\n",
    "REPORT_PREFIX = \"rp\"\n",
    "INDICATOR_PREFIX = \"ind\"\n",
    "AUDIT_PREFIX = \"audit\"\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# Column naming standards\n",
    "COLUMN_TYPE_PATTERNS = {\n",
    "    \"id\": \"identifier\",\n",
    "    \"cd\": \"code\",\n",
    "    \"tx\": \"text\",\n",
    "    \"dt\": \"date\",\n",
    "    \"ts\": \"timestamp\",\n",
    "    \"vl\": \"value\",\n",
    "    \"qt\": \"quantity\",\n",
    "    \"pc\": \"percentage\",\n",
    "    \"fl\": \"flag\",\n",
    "    \"nr\": \"number\"\n",
    "}\n",
    "\n",
    "MNEMONICS = {\n",
    "    \"dept\": \"deputy\",\n",
    "    \"prt\": \"party\",\n",
    "    \"uf\": \"state\",\n",
    "    \"leg\": \"legislature\",\n",
    "    \"frnt\": \"front\",\n",
    "    \"evt\": \"event\",\n",
    "    \"vot\": \"voting\",\n",
    "    \"vote\": \"voting result\",\n",
    "    \"dsp\": \"expense\",\n",
    "    \"forn\": \"supplier\",\n",
    "    \"cpi\": \"parliamentary inquiry commission\",\n",
    "    \"prop\": \"proposition\",\n",
    "    \"org\": \"organization\",\n",
    "    \"aud\": \"audit\",\n",
    "    \"qlt\": \"quality\",\n",
    "    \"err\": \"error\"\n",
    "}\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# API configuration\n",
    "API_BASE_URL = \"https://dadosabertos.camara.leg.br/api/v2\"\n",
    "API_TIMEOUT_SECONDS = 120\n",
    "API_PAGE_SIZE = 100\n",
    "API_MAX_RETRIES = 3\n",
    "\n",
    "API_ENDPOINTS = {\n",
    "    \"deputies\": \"/deputados\",\n",
    "    \"fronts\": \"/frentes\",\n",
    "    \"front_members\": \"/frentes/{id}/membros\",\n",
    "    \"events\": \"/eventos\",\n",
    "    \"votings\": \"/votacoes\",\n",
    "    \"voting_results\": \"/votacoes/{id}/votos\",\n",
    "    \"expenses_ceap\": \"/deputados/{id}/despesas\",\n",
    "    \"cpis\": \"/orgaos\",\n",
    "    \"cpi_events\": \"/eventos\",\n",
    "    \"propositions\": \"/proposicoes\"\n",
    "}\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# Audit tables\n",
    "AUDIT_PIPELINE_LOGS = f\"{AUDIT_SCHEMA}.audit_pipeline_logs\"\n",
    "AUDIT_PIPELINE_ERRORS = f\"{AUDIT_SCHEMA}.audit_pipeline_errors\"\n",
    "AUDIT_DATA_QUALITY_LOGS = f\"{AUDIT_SCHEMA}.audit_data_quality_logs\"\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# Traceability columns\n",
    "TRACEABILITY_COLUMNS = [\n",
    "    \"aud_id_execution\",\n",
    "    \"aud_ts_ingestion\",\n",
    "    \"aud_ts_processing\",\n",
    "    \"aud_tx_source_endpoint\",\n",
    "    \"aud_tx_source_system\",\n",
    "    \"aud_tx_pipeline_version\",\n",
    "    \"aud_hash_record\"\n",
    "]\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# Physical table names - Bronze\n",
    "BRONZE_TABLES = {\n",
    "    \"deputies\": \"bronze_deputies_raw\",\n",
    "    \"fronts\": \"bronze_fronts_raw\",\n",
    "    \"front_members\": \"bronze_front_members_raw\",\n",
    "    \"events\": \"bronze_events_raw\",\n",
    "    \"votings\": \"bronze_votings_raw\",\n",
    "    \"voting_results\": \"bronze_voting_results_raw\",\n",
    "    \"expenses_ceap\": \"bronze_expenses_ceap_raw\",\n",
    "    \"cpis\": \"bronze_cpis_raw\",\n",
    "    \"cpi_events\": \"bronze_cpi_events_raw\",\n",
    "    \"propositions\": \"bronze_propositions_raw\"\n",
    "}\n",
    "\n",
    "# Physical table names - Silver Base\n",
    "SILVER_BASE_TABLES = {\n",
    "    \"deputies\": \"silver_base_deputies\",\n",
    "    \"fronts\": \"silver_base_fronts\",\n",
    "    \"front_members\": \"silver_base_front_members\",\n",
    "    \"events\": \"silver_base_events\",\n",
    "    \"votings\": \"silver_base_votings\",\n",
    "    \"voting_results\": \"silver_base_voting_results\",\n",
    "    \"expenses_ceap\": \"silver_base_expenses_ceap\",\n",
    "    \"cpis\": \"silver_base_cpis\",\n",
    "    \"cpi_events\": \"silver_base_cpi_events\",\n",
    "    \"propositions\": \"silver_base_propositions\"\n",
    "}\n",
    "\n",
    "# Physical table names - Silver Curated\n",
    "SILVER_CURATED_TABLES = {\n",
    "    \"deputies\": \"silver_curated_deputies\",\n",
    "    \"parties\": \"silver_curated_parties\",\n",
    "    \"states\": \"silver_curated_states\",\n",
    "    \"fronts\": \"silver_curated_fronts\",\n",
    "    \"events\": \"silver_curated_events\",\n",
    "    \"votings\": \"silver_curated_votings\",\n",
    "    \"voting_results\": \"silver_curated_voting_results\",\n",
    "    \"expenses_ceap\": \"silver_curated_expenses_ceap\",\n",
    "    \"cpis\": \"silver_curated_cpis\",\n",
    "    \"propositions\": \"silver_curated_propositions\"\n",
    "}\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# Gold tables\n",
    "GOLD_DIMENSIONS = {\n",
    "    \"deputy\": \"dm_deputy\",\n",
    "    \"party\": \"dm_party\",\n",
    "    \"state\": \"dm_state\",\n",
    "    \"date\": \"dm_date\",\n",
    "    \"front\": \"dm_front\",\n",
    "    \"event\": \"dm_event\",\n",
    "    \"voting\": \"dm_voting\",\n",
    "    \"cpi\": \"dm_cpi\",\n",
    "    \"supplier\": \"dm_supplier\"\n",
    "}\n",
    "\n",
    "GOLD_FACTS = {\n",
    "    \"front_members\": \"ft_front_members\",\n",
    "    \"event_attendance\": \"ft_event_attendance\",\n",
    "    \"voting_results\": \"ft_voting_results\",\n",
    "    \"expenses_ceap\": \"ft_expenses_ceap\",\n",
    "    \"cpi_events\": \"ft_cpi_events\"\n",
    "}\n",
    "\n",
    "ANALYTICAL_MARTS = {\n",
    "    \"fronts_atlas\": \"am_fronts_atlas\",\n",
    "    \"events_calendar\": \"am_legislative_events_calendar\",\n",
    "    \"fronts_votings_correlation\": \"am_fronts_votings_correlation\",\n",
    "    \"ceap_expenses_overview\": \"am_ceap_expenses_overview\",\n",
    "    \"cpi_audit\": \"am_cpi_audit\",\n",
    "    \"attendance_absenteeism_monitor\": \"am_attendance_absenteeism_monitor\"\n",
    "}\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# Default processing configuration\n",
    "DEFAULT_FILE_FORMAT = \"delta\"\n",
    "DEFAULT_WRITE_MODE = \"overwrite\"\n",
    "\n",
    "ENABLE_TABLE_COMMENTS = True\n",
    "ENABLE_COLUMN_COMMENTS = True\n",
    "ENABLE_TRACEABILITY = True\n",
    "ENABLE_PIPELINE_LOGGING = True\n",
    "ENABLE_ERROR_LOGGING = True\n",
    "ENABLE_DATA_QUALITY_LOGGING = True\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "print(\"=\" * 80)\n",
    "print(\"BRAZIL LEGISLATIVE ANALYTICS MEDALLION\")\n",
    "print(\"01 - PROJECT CONFIGURATION\")\n",
    "print(\"=\" * 80)\n",
    "print(f\"Project Name: {PROJECT_NAME}\")\n",
    "print(f\"Project Code: {PROJECT_CODE}\")\n",
    "print(f\"Environment: {ENVIRONMENT}\")\n",
    "print(f\"Pipeline Version: {PIPELINE_VERSION}\")\n",
    "print(f\"Execution Timestamp: {EXECUTION_TIMESTAMP}\")\n",
    "print(f\"Run ID: {RUN_ID}\")\n",
    "print(\"=\" * 80)\n",
    "print(f\"Catalog: {CATALOG_NAME}\")\n",
    "print(f\"Audit Schema: {AUDIT_SCHEMA}\")\n",
    "print(f\"Bronze Schema: {BRONZE_SCHEMA}\")\n",
    "print(f\"Silver Base Schema: {SILVER_BASE_SCHEMA}\")\n",
    "print(f\"Silver Curated Schema: {SILVER_CURATED_SCHEMA}\")\n",
    "print(f\"Gold Schema: {GOLD_SCHEMA}\")\n",
    "print(f\"Marts Schema: {MARTS_SCHEMA}\")\n",
    "print(\"=\" * 80)\n",
    "print(\"PROJECT CONFIGURATION LOADED SUCCESSFULLY\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %md\n",
    "# MAGIC ## Configuration Loaded\n",
    "# MAGIC\n",
    "# MAGIC This notebook defines reusable variables for:\n",
    "# MAGIC\n",
    "# MAGIC - Catalog and schemas\n",
    "# MAGIC - API endpoints\n",
    "# MAGIC - Audit tables\n",
    "# MAGIC - Naming conventions\n",
    "# MAGIC - Physical table names\n",
    "# MAGIC - Traceability columns\n",
    "# MAGIC - Gold dimensions, facts and analytical marts"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "01_project_config",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}