{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "66e45646-4403-455a-a722-a65599b8cbbd",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "================================================================================\nBRAZIL LEGISLATIVE ANALYTICS MEDALLION\n02 - CREATE AUDIT TABLES\n================================================================================\nExecution Timestamp: 2026-05-17 04:30:48.745812\nCatalog: brazil_legislative_analytics\nAudit Schema: brazil_legislative_analytics.audit\n================================================================================\n"
     ]
    },
    {
     "output_type": "display_data",
     "data": {
      "text/html": [
       "<style scoped>\n",
       "  .table-result-container {\n",
       "    max-height: 300px;\n",
       "    overflow: auto;\n",
       "  }\n",
       "  table, th, td {\n",
       "    border: 1px solid black;\n",
       "    border-collapse: collapse;\n",
       "  }\n",
       "  th, td {\n",
       "    padding: 5px;\n",
       "  }\n",
       "  th {\n",
       "    text-align: left;\n",
       "  }\n",
       "</style><div class='table-result-container'><table class='table-result'><thead style='background-color: white'><tr><th>database</th><th>tableName</th><th>isTemporary</th></tr></thead><tbody><tr><td>audit</td><td>audit_data_quality_logs</td><td>false</td></tr><tr><td>audit</td><td>audit_pipeline_errors</td><td>false</td></tr><tr><td>audit</td><td>audit_pipeline_logs</td><td>false</td></tr></tbody></table></div>"
      ]
     },
     "metadata": {
      "application/vnd.databricks.v1+output": {
       "addedWidgets": {},
       "aggData": [],
       "aggError": "",
       "aggOverflow": false,
       "aggSchema": [],
       "aggSeriesLimitReached": false,
       "aggType": "",
       "arguments": {},
       "columnCustomDisplayInfos": {},
       "data": [
        [
         "audit",
         "audit_data_quality_logs",
         false
        ],
        [
         "audit",
         "audit_pipeline_errors",
         false
        ],
        [
         "audit",
         "audit_pipeline_logs",
         false
        ]
       ],
       "datasetInfos": [],
       "dbfsResultPath": null,
       "isJsonSchema": true,
       "metadata": {},
       "overflow": false,
       "plotOptions": {
        "customPlotOptions": {},
        "displayType": "table",
        "pivotAggregation": null,
        "pivotColumns": null,
        "xColumns": null,
        "yColumns": null
       },
       "removedWidgets": [],
       "schema": [
        {
         "metadata": "{}",
         "name": "database",
         "type": "\"string\""
        },
        {
         "metadata": "{}",
         "name": "tableName",
         "type": "\"string\""
        },
        {
         "metadata": "{}",
         "name": "isTemporary",
         "type": "\"boolean\""
        }
       ],
       "type": "table"
      }
     },
     "output_type": "display_data"
    },
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "================================================================================\nAUDIT TABLES CREATED SUCCESSFULLY\n================================================================================\nTable: brazil_legislative_analytics.audit.audit_pipeline_logs\nTable: brazil_legislative_analytics.audit.audit_pipeline_errors\nTable: brazil_legislative_analytics.audit.audit_data_quality_logs\n================================================================================\n"
     ]
    }
   ],
   "source": [
    "# Databricks notebook source\n",
    "# MAGIC %md\n",
    "# MAGIC # 02_audit_tables\n",
    "# MAGIC\n",
    "# MAGIC ## Purpose\n",
    "# MAGIC Create audit and governance tables used to monitor pipeline executions,\n",
    "# MAGIC pipeline errors and data quality validations across all Medallion layers.\n",
    "# MAGIC\n",
    "# MAGIC ## Layer\n",
    "# MAGIC Setup / Audit\n",
    "# MAGIC\n",
    "# MAGIC ## Inputs\n",
    "# MAGIC - `01_project_config`\n",
    "# MAGIC\n",
    "# MAGIC ## Outputs\n",
    "# MAGIC - `audit_pipeline_logs`\n",
    "# MAGIC - `audit_pipeline_errors`\n",
    "# MAGIC - `audit_data_quality_logs`\n",
    "# MAGIC\n",
    "# MAGIC ## Documentation Standard\n",
    "# MAGIC All tables and columns include comments for governance and traceability.\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %run ./01_project_config\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "from datetime import datetime\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# Safety fallback to avoid undefined variables in Databricks notebook context.\n",
    "CATALOG_NAME = globals().get(\"CATALOG_NAME\", \"brazil_legislative_analytics\")\n",
    "AUDIT_SCHEMA = globals().get(\"AUDIT_SCHEMA\", f\"{CATALOG_NAME}.audit\")\n",
    "\n",
    "AUDIT_PIPELINE_LOGS = globals().get(\n",
    "    \"AUDIT_PIPELINE_LOGS\",\n",
    "    f\"{AUDIT_SCHEMA}.audit_pipeline_logs\"\n",
    ")\n",
    "\n",
    "AUDIT_PIPELINE_ERRORS = globals().get(\n",
    "    \"AUDIT_PIPELINE_ERRORS\",\n",
    "    f\"{AUDIT_SCHEMA}.audit_pipeline_errors\"\n",
    ")\n",
    "\n",
    "AUDIT_DATA_QUALITY_LOGS = globals().get(\n",
    "    \"AUDIT_DATA_QUALITY_LOGS\",\n",
    "    f\"{AUDIT_SCHEMA}.audit_data_quality_logs\"\n",
    ")\n",
    "\n",
    "spark.sql(f\"USE CATALOG {CATALOG_NAME}\")\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "print(\"=\" * 80)\n",
    "print(\"BRAZIL LEGISLATIVE ANALYTICS MEDALLION\")\n",
    "print(\"02 - CREATE AUDIT TABLES\")\n",
    "print(\"=\" * 80)\n",
    "print(f\"Execution Timestamp: {datetime.now()}\")\n",
    "print(f\"Catalog: {CATALOG_NAME}\")\n",
    "print(f\"Audit Schema: {AUDIT_SCHEMA}\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %md\n",
    "# MAGIC ## 1. Create Pipeline Logs Table\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "spark.sql(f\"\"\"\n",
    "CREATE TABLE IF NOT EXISTS {AUDIT_PIPELINE_LOGS} (\n",
    "    aud_id_log STRING COMMENT 'Unique identifier for the pipeline log record.',\n",
    "    aud_id_run STRING COMMENT 'Unique execution identifier shared across notebooks within the same pipeline run.',\n",
    "    aud_tx_project_name STRING COMMENT 'Project name associated with the execution.',\n",
    "    aud_tx_pipeline_version STRING COMMENT 'Pipeline version executed.',\n",
    "    aud_tx_environment STRING COMMENT 'Execution environment, such as dev, qa or prod.',\n",
    "    aud_tx_notebook_name STRING COMMENT 'Notebook responsible for the execution.',\n",
    "    aud_tx_layer_name STRING COMMENT 'Medallion layer executed: setup, bronze, silver_base, silver_curated, gold, marts or quality.',\n",
    "    aud_tx_entity_name STRING COMMENT 'Business or technical entity processed during execution.',\n",
    "    aud_tx_target_table STRING COMMENT 'Fully qualified target table processed during execution.',\n",
    "    aud_tx_status STRING COMMENT 'Execution status: STARTED, SUCCESS, FAILED or WARNING.',\n",
    "    aud_ts_start TIMESTAMP COMMENT 'Execution start timestamp.',\n",
    "    aud_ts_end TIMESTAMP COMMENT 'Execution end timestamp.',\n",
    "    aud_nr_duration_seconds DOUBLE COMMENT 'Execution duration in seconds.',\n",
    "    aud_qt_records_read BIGINT COMMENT 'Number of records read during processing.',\n",
    "    aud_qt_records_written BIGINT COMMENT 'Number of records written during processing.',\n",
    "    aud_tx_message STRING COMMENT 'Additional execution message or processing note.'\n",
    ")\n",
    "USING DELTA\n",
    "COMMENT 'Audit table responsible for storing pipeline execution history across all Medallion layers.'\n",
    "\"\"\")\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %md\n",
    "# MAGIC ## 2. Create Pipeline Errors Table\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "spark.sql(f\"\"\"\n",
    "CREATE TABLE IF NOT EXISTS {AUDIT_PIPELINE_ERRORS} (\n",
    "    err_id_error STRING COMMENT 'Unique identifier for the error record.',\n",
    "    aud_id_run STRING COMMENT 'Execution identifier associated with the failed pipeline execution.',\n",
    "    aud_tx_project_name STRING COMMENT 'Project name associated with the error.',\n",
    "    aud_tx_pipeline_version STRING COMMENT 'Pipeline version executed.',\n",
    "    aud_tx_environment STRING COMMENT 'Execution environment where the error occurred.',\n",
    "    aud_tx_notebook_name STRING COMMENT 'Notebook where the error occurred.',\n",
    "    aud_tx_layer_name STRING COMMENT 'Medallion layer where the error occurred.',\n",
    "    aud_tx_entity_name STRING COMMENT 'Business or technical entity being processed when the error occurred.',\n",
    "    aud_tx_target_table STRING COMMENT 'Fully qualified target table associated with the error.',\n",
    "    err_tx_step_name STRING COMMENT 'Pipeline step where the error occurred.',\n",
    "    err_tx_error_type STRING COMMENT 'Error classification or exception type.',\n",
    "    err_tx_message STRING COMMENT 'Error message returned during execution.',\n",
    "    err_tx_stacktrace STRING COMMENT 'Complete stack trace captured for troubleshooting.',\n",
    "    err_ts_occurrence TIMESTAMP COMMENT 'Timestamp when the error occurred.'\n",
    ")\n",
    "USING DELTA\n",
    "COMMENT 'Audit table responsible for storing pipeline execution errors and troubleshooting details.'\n",
    "\"\"\")\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %md\n",
    "# MAGIC ## 3. Create Data Quality Logs Table\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "spark.sql(f\"\"\"\n",
    "CREATE TABLE IF NOT EXISTS {AUDIT_DATA_QUALITY_LOGS} (\n",
    "    qlt_id_log STRING COMMENT 'Unique identifier for the quality validation log.',\n",
    "    aud_id_run STRING COMMENT 'Execution identifier associated with the quality validation.',\n",
    "    aud_tx_project_name STRING COMMENT 'Project name associated with the validation.',\n",
    "    aud_tx_pipeline_version STRING COMMENT 'Pipeline version executed.',\n",
    "    aud_tx_environment STRING COMMENT 'Execution environment associated with the validation.',\n",
    "    aud_tx_notebook_name STRING COMMENT 'Notebook responsible for executing the quality validation.',\n",
    "    aud_tx_layer_name STRING COMMENT 'Medallion layer validated.',\n",
    "    aud_tx_entity_name STRING COMMENT 'Business or technical entity validated.',\n",
    "    aud_tx_target_table STRING COMMENT 'Fully qualified table validated.',\n",
    "    qlt_tx_rule_name STRING COMMENT 'Name of the executed data quality rule.',\n",
    "    qlt_tx_rule_description STRING COMMENT 'Description of the executed data quality rule.',\n",
    "    qlt_tx_validation_status STRING COMMENT 'Validation result: PASSED, FAILED or WARNING.',\n",
    "    qlt_qt_total_records BIGINT COMMENT 'Total number of records evaluated.',\n",
    "    qlt_qt_invalid_records BIGINT COMMENT 'Number of invalid records identified.',\n",
    "    qlt_pc_invalid_records DOUBLE COMMENT 'Percentage of invalid records identified during validation.',\n",
    "    qlt_ts_validation TIMESTAMP COMMENT 'Timestamp when the validation was executed.',\n",
    "    qlt_tx_message STRING COMMENT 'Additional validation message or observation.'\n",
    ")\n",
    "USING DELTA\n",
    "COMMENT 'Audit table responsible for storing data quality validation results across all Medallion layers.'\n",
    "\"\"\")\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %md\n",
    "# MAGIC ## 4. Validate Created Tables\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "audit_tables_df = spark.sql(f\"\"\"\n",
    "SHOW TABLES IN {AUDIT_SCHEMA}\n",
    "\"\"\")\n",
    "\n",
    "display(audit_tables_df)\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "print(\"=\" * 80)\n",
    "print(\"AUDIT TABLES CREATED SUCCESSFULLY\")\n",
    "print(\"=\" * 80)\n",
    "print(f\"Table: {AUDIT_PIPELINE_LOGS}\")\n",
    "print(f\"Table: {AUDIT_PIPELINE_ERRORS}\")\n",
    "print(f\"Table: {AUDIT_DATA_QUALITY_LOGS}\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "# COMMAND ----------\n",
    "\n",
    "# MAGIC %md\n",
    "# MAGIC ## Governance Notes\n",
    "# MAGIC\n",
    "# MAGIC These audit tables support:\n",
    "# MAGIC\n",
    "# MAGIC - Operational monitoring\n",
    "# MAGIC - Error traceability\n",
    "# MAGIC - Data governance\n",
    "# MAGIC - Data quality controls\n",
    "# MAGIC - Pipeline observability\n",
    "# MAGIC\n",
    "# MAGIC ## Standards Applied\n",
    "# MAGIC\n",
    "# MAGIC - Delta format\n",
    "# MAGIC - Table comments\n",
    "# MAGIC - Column comments\n",
    "# MAGIC - Mnemonic naming convention\n",
    "# MAGIC - Medallion governance standard\n",
    "# MAGIC\n",
    "# MAGIC ## Next Step\n",
    "# MAGIC Execute:\n",
    "# MAGIC\n",
    "# MAGIC `90_validate_project_setup`"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "02_audit_tables",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}